# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Horizontal Flight Merge
                                 A QGIS plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-24
        copyright            : (C) 2025 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França - Participação Ilton Freitas'
__date__ = '2025-11-24'
__copyright__ = '(C) 2025 by Prof Cazaroli e Leandro França - Participação Ilton Freitas'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from ..images.Imgs import *
import csv
import os
from .Funcs import loadParametros, saveParametros, csv_como_layer, criar_layer_path

class CSV_Merge(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        csv1Merge, csv2Merge, addCsvMerge, addPointsMerge = loadParametros("H_Merge")
       
        self.addParameter(QgsProcessingParameterFile(
            'csv1', 
            'Enter the first CSV file', 
            behavior=QgsProcessingParameterFile.File, 
            fileFilter='CSV Files (*.csv)', 
            defaultValue=csv1Merge
        ))
        self.addParameter(QgsProcessingParameterFile(
            'csv2', 
            'Enter the second CSV file', 
            behavior=QgsProcessingParameterFile.File, 
            fileFilter='CSV Files (*.csv)', 
            defaultValue=csv2Merge
        ))
        self.addParameter(QgsProcessingParameterFileDestination(
            'csvS', 
            'Simplified CSV', 
            fileFilter='CSV Files (*.csv)', 
            defaultValue=addCsvMerge 
        ))
        self.addParameter(QgsProcessingParameterBoolean(
            'ver_Points_merge', 
            'Add merged points layer to project', 
            defaultValue=addPointsMerge
        ))

    def processAlgorithm(self, parameters, context, feedback):
        arquivo_csv1 = self.parameterAsFile(parameters, 'csv1', context)
        arquivo_csv2 = self.parameterAsFile(parameters, 'csv2', context)
        arquivo_csvS = self.parameterAsFile(parameters, 'csvS', context)

        # Verificações
        if not arquivo_csv1 or not os.path.exists(arquivo_csv1):
            raise QgsProcessingException("❌ First CSV file not found!")
        
        if not arquivo_csv2 or not os.path.exists(arquivo_csv2):
            raise QgsProcessingException("❌ Second CSV file not found!")
        
        if arquivo_csvS and not os.path.exists(os.path.dirname(arquivo_csvS)):
            raise QgsProcessingException("❌ Path to output CSV does not exist!")
        
        # Grava Parâmetros
        saveParametros("H_Merge",
                        csvI=arquivo_csv1,
                        csv=arquivo_csv2,
                        add1=arquivo_csvS,
                        add2=parameters['ver_Points_merge']
                        )
                                
        # =========================================================================
        # Processo: juntar os dois CSV em um terceiro
        with open(arquivo_csv1, 'r', encoding='utf-8') as f1, \
             open(arquivo_csv2, 'r', encoding='utf-8') as f2:

            reader1 = csv.reader(f1)
            reader2 = csv.reader(f2)

            header1 = next(reader1)
            header2 = next(reader2)

            header_out = header1 if header1 == header2 else header1 + [h for h in header2 if h not in header1]

            with open(arquivo_csvS, 'w', newline='', encoding='utf-8') as fout:
                writer = csv.writer(fout)
                writer.writerow(header_out)
                rows1 = list(reader1)
                rows2 = list(reader2)

                # Escrever linhas do primeiro CSV
                for row in rows1:
                    writer.writerow(row)

                # Ponto de conexão entre os dois voos
                # Usa o último ponto do voo 1 e o primeiro do voo 2
                # e interpola um waypoint intermediário
                if rows1 and rows2:
                    try:
                        idx_lon = header_out.index('longitude')
                        idx_lat = header_out.index('latitude')
                        idx_alt = header_out.index('altitude(m)')

                        last = rows1[-1]
                        first = rows2[0]

                        lon_mid = (float(last[idx_lon]) + float(first[idx_lon])) / 2
                        lat_mid = (float(last[idx_lat]) + float(first[idx_lat])) / 2
                        alt_mid = max(float(last[idx_alt]), float(first[idx_alt]))

        # =========================================================================
        # Criar ponto de conexão baseado no último ponto do voo 1
                        import math
                        idx_heading = header_out.index('heading(deg)') if 'heading(deg)' in header_out else None

                        # Calcular heading do ponto médio para o primeiro ponto do voo 2
                        dx = float(first[idx_lon]) - lon_mid
                        dy = float(first[idx_lat]) - lat_mid
                        heading_mid = int((math.degrees(math.atan2(dx, dy)) + 360) % 360)

                        row_mid = list(last)
                        row_mid[idx_lon] = f"{lon_mid:.8f}"
                        row_mid[idx_lat] = f"{lat_mid:.8f}"
                        row_mid[idx_alt] = f"{alt_mid:.1f}"
                        if idx_heading is not None:
                            row_mid[idx_heading] = str(heading_mid)
                        writer.writerow(row_mid)
                    except Exception as e:
                        feedback.reportError(f"⚠️ Could not create connection waypoint: {str(e)}")

                # Escrever linhas do segundo CSV
                for row in rows2:
                    writer.writerow(row)

        n_total = len(rows1) + len(rows2)
        feedback.pushInfo(f"✅ Merged {len(rows1)} + {len(rows2)} = {n_total} waypoints")

        # =========================================================================
        # Camadas no QGIS
        import processing

        csv_name = os.path.splitext(os.path.basename(arquivo_csvS))[0]

        # Camada de pontos
        if parameters['ver_Points_merge']:
            layer_pontos = csv_como_layer(arquivo_csvS, layer_name=None)
            if layer_pontos is None or not layer_pontos.isValid():
                feedback.reportError("❌ Could not load merged CSV as point layer.")
            else:
                QgsProject.instance().addMapLayer(layer_pontos)
                feedback.pushInfo("✅ Merged points layer added to QGIS.")
                try:
                    processing.run("lftools:magicstyles", {'LAYER': layer_pontos, 'STYLE_POINT': 1})
                except:
                    feedback.reportError("💡 Install or enable the LFTools plugin to view the drone's heading.")

        # Linha de voo — construir LISTA_PONTOS a partir do CSV merged
        try:
            LISTA_PONTOS = []
            with open(arquivo_csvS, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    try:
                        LISTA_PONTOS.append({
                            'longitude': float(row['longitude']),
                            'latitude':  float(row['latitude']),
                            'height':    float(row['altitude(m)']),
                            'bowangle':  0
                        })
                    except:
                        continue

            layer_path = criar_layer_path(LISTA_PONTOS, arquivo_csvS)
            layer_path.setName(f"path - {csv_name}")
            QgsProject.instance().addMapLayer(layer_path)
            feedback.pushInfo("✅ Flight path layer added to QGIS.")
        except Exception as e:
            feedback.reportError(f"⚠️ Could not create flight path layer: {str(e)}")

        feedback.pushInfo("")
        feedback.pushInfo("✅ CSV Merge executed successfully.")
        feedback.pushInfo("")

        return {}

    def name(self):
        return 'MergeCSV'.lower()

    def displayName(self):
        return self.tr('2. Merge CSV files')

    def group(self):
        return 'CSV Tools'

    def groupId(self):
        return 'CSVTools'.lower()

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CSV_Merge()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drones,GeoOne,simplify,simplificar,generalize,merge').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/CSV.png'))
    
    figura2 = 'images/csv_merge.jpg'

    def shortHelpString(self):
        texto = f"""This tool allows you to <b>merge two flight plan CSV files into a single mission</b>,
    enabling them to be executed <b>sequentially in one continuous flight</b>.
    <p>
    It is especially useful for <b>mapping missions</b>, where one area is flown first
    and the drone continues directly to the next area <b>without returning to the takeoff point</b>.
    </p>
    <p>
    By combining multiple flight plans into a single CSV, you can <b>optimize flight time</b>,
    <b>reduce unnecessary maneuvers</b>, and <b>save battery</b>, making large surveys more efficient.
    </p>
    <p>
    The merged CSV also can be loaded into QGIS as a <b>point layer</b> for quick visual validation.
    </p>
        """

        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura2) +'''">
                      </div>
                      <div align="right">
                       <p><b>Learn more:</b></p>
                        <ul>
                            <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a></li>
                            <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6027">Click here to access the class with all the details about this tool!</a></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli, Leandro França and Ilton Freitas</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''

        return self.tr(texto) + corpo