# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Horizontal Flight Simplified
                                 A QGIS plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-17
        copyright            : (C) 2025 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França - Participação Ilton Freitas'
__date__ = '2025-09-17'
__copyright__ = '(C) 2025 by Prof Cazaroli e Leandro França - Participação Ilton Freitas'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from ..images.Imgs import *
import csv
import os
import tempfile
import uuid
from .Funcs import loadParametros, saveParametros, csv_como_layer

class CSV_Simplify(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        csvInSimplified, csvOutSimplified, rasterSimplified, toleranceSimplified, addPCsvSimplified, addPSimplified, addLSimplified = loadParametros("H_Simplified")
       
        self.addParameter(QgsProcessingParameterFile(
            'voo_em_csv', 'Generated CSV file',
            behavior=QgsProcessingParameterFile.File,
            fileFilter='CSV Files (*.csv)',
            defaultValue=csvInSimplified
        ))
        self.addParameter(QgsProcessingParameterRasterLayer(
            'dem', 'Digital Elevation Model (DEM)',
            defaultValue=rasterSimplified
        ))
        self.addParameter(QgsProcessingParameterCrs(
            'src_projetado', 'Projected Coordinate Reference System (CRS)',
            defaultValue=QgsProject.instance().crs()
        ))
        self.addParameter(QgsProcessingParameterNumber(
            'tolerancia', 'Tolerance',
            type=QgsProcessingParameterNumber.Double,
            defaultValue=toleranceSimplified
        ))
        self.addParameter(QgsProcessingParameterFileDestination(
            'csv_saida', 'Simplified CSV',
            fileFilter='CSV Files (*.csv)',
            defaultValue=csvOutSimplified
        ))
        self.addParameter(QgsProcessingParameterBoolean(
            'adicionar_pontos_csv', 'Add CSV points layer to project',
            defaultValue=addPCsvSimplified
        ))
        self.addParameter(QgsProcessingParameterBoolean(
            'adicionar_linha_trajetoria', 'Add flight line layer to project',
            defaultValue=addLSimplified
        ))
        self.addParameter(QgsProcessingParameterBoolean(
            'adicionar_pontos_simplificados', 'Add simplified points layer to project',
            defaultValue=addPSimplified
        ))

    def processAlgorithm(self, parameters, context, model_feedback):
        arquivo_csvIn = self.parameterAsFile(parameters, 'voo_em_csv', context)
        arquivo_csvOut = self.parameterAsFile(parameters, 'csv_saida', context)
        arquivo_DEM = self.parameterAsFile(parameters, 'dem', context)

        if 'voo_em_csv' not in parameters:
            raise QgsProcessingException("\u274c Generated CSV file is empty!")
        if arquivo_csvIn and not os.path.exists(os.path.dirname(arquivo_csvIn)):
            raise QgsProcessingException("\u274c Path to Generated CSV file does not exist!")
        if 'dem' not in parameters:
            raise QgsProcessingException("\u274c DEM is empty!")
        if 'src_projetado' not in parameters:
            raise QgsProcessingException("\u274c CRS is empty!")
        if 'tolerancia' not in parameters:
            raise QgsProcessingException("\u274c Tolerance is empty!")
        if 'csv_saida' not in parameters:
            raise QgsProcessingException("\u274c Output CSV path is empty!")
        if arquivo_csvOut and not os.path.exists(os.path.dirname(arquivo_csvOut)):
            raise QgsProcessingException("\u274c Path to Simplified CSV file does not exist!")

        saveParametros("H_Simplified",
                        csvI=arquivo_csvIn,
                        csv=arquivo_csvOut,
                        raster=arquivo_DEM,
                        crs=parameters['src_projetado'],
                        tol=parameters['tolerancia'],
                        add1=parameters['adicionar_pontos_csv'],
                        add2=parameters['adicionar_linha_trajetoria'],
                        add3=parameters['adicionar_pontos_simplificados'])

        feedback = QgsProcessingMultiStepFeedback(13, model_feedback)
        results = {}
        outputs = {}
        temp_files = []

        feedback.pushInfo("=" * 50)
        feedback.pushInfo("STARTING 3D SIMPLIFICATION PROCESSING")
        feedback.pushInfo("=" * 50)

        # ETAPA 1: Criar pontos a partir do CSV
        feedback.pushInfo("STEP 1: Creating points from CSV...")
        try:
            csv_path = self.parameterAsString(parameters, 'voo_em_csv', context)
            with open(csv_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                fields = reader.fieldnames

            for field in ['longitude', 'latitude', 'altitude(m)']:
                if field not in fields:
                    raise QgsProcessingException(f"Field {field} not found in CSV")

            temp_layer = QgsVectorLayer("PointZ?crs=EPSG:4326", "temp_points", "memory")
            provider = temp_layer.dataProvider()
            new_fields = QgsFields()
            for field in fields:
                new_fields.append(QgsField(field, QVariant.String))
            new_fields.append(QgsField('original_index', QVariant.Int))
            provider.addAttributes(new_fields)
            temp_layer.updateFields()

            features = []
            with open(csv_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.DictReader(csvfile)
                for idx, row in enumerate(reader):
                    try:
                        x = float(row['longitude'])
                        y = float(row['latitude'])
                        z = float(row['altitude(m)'])
                        feat = QgsFeature()
                        feat.setGeometry(QgsGeometry(QgsPoint(x, y, z)))
                        feat.setAttributes([row[f] for f in fields] + [idx + 1])
                        features.append(feat)
                    except Exception as e:
                        feedback.pushWarning(f"Error in line {idx + 1}: {str(e)}")

            provider.addFeatures(features)
            temp_layer.updateExtents()

            temp_file = os.path.join(tempfile.gettempdir(), f'temp_points_{uuid.uuid4().hex}.gpkg')
            temp_files.append(temp_file)
            if os.path.exists(temp_file):
                os.remove(temp_file)

            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = "GPKG"
            writer = QgsVectorFileWriter.writeAsVectorFormat(temp_layer, temp_file, options)
            if writer[0] != QgsVectorFileWriter.NoError:
                raise QgsProcessingException(f"Error saving temporary file: {writer}")

            outputs['CriarPontosAPartirDeCsv'] = {'OUTPUT': temp_file}
            feedback.pushInfo("\u2713 Points created successfully")

            if parameters['adicionar_pontos_csv']:
                pontos_csv_layer = QgsVectorLayer(temp_file, 'pontos_csv', 'ogr')
                if pontos_csv_layer.isValid():
                    csv_name = os.path.splitext(os.path.basename(csv_path))[0]
                    pontos_csv_layer.setName(f"{csv_name} - Original CSV")
                    QgsProject.instance().addMapLayer(pontos_csv_layer)
                    try:
                        import processing
                        processing.run("lftools:magicstyles", {'LAYER': pontos_csv_layer, 'STYLE_POINT': 1})
                        feedback.pushInfo("\u2713 CSV point layer added to project")
                    except:
                        feedback.reportError("\U0001f4a1 Install or enable the LFTools plugin to view the drone's heading.")

        except Exception as e:
            feedback.reportError(f"Error creating points: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(1)
        if feedback.isCanceled(): return {}

        # ETAPA 2: Campo de índice (já feito na etapa 1)
        feedback.pushInfo("STEP 2: Index field already added...")
        outputs['AdicionarIndice'] = {'OUTPUT': temp_file}
        feedback.pushInfo("\u2713 Index field already exists")
        feedback.setCurrentStep(2)
        if feedback.isCanceled(): return {}

        # ETAPA 3: Amostrar valores do raster com LFTools
        import processing
        feedback.pushInfo("STEP 3: Sampling raster values with LFTools...")
        try:
            pontos_layer = QgsVectorLayer(outputs['AdicionarIndice']['OUTPUT'], 'pontos', 'ogr')
            temp_file_amostrado = os.path.join(tempfile.gettempdir(), f'pontos_amostrados_{uuid.uuid4().hex}.gpkg')
            temp_files.append(temp_file_amostrado)
            if os.path.exists(temp_file_amostrado): os.remove(temp_file_amostrado)

            outputs['AmostrarRaster'] = processing.run("lftools:getpointvalue", {
                'INPUT': parameters['dem'], 'BAND': 1, 'POINTS': pontos_layer,
                'RESAMPLING': 1, 'PREFIX': 'sample_', 'OUTPUT': temp_file_amostrado
            }, context=context, feedback=feedback, is_child_algorithm=True)

            if os.path.exists(temp_file_amostrado):
                feedback.pushInfo("\u2713 Raster values successfully sampled")
            else:
                feedback.reportError("Failed to create temporary file with sampled values")
                return {}
        except Exception as e:
            feedback.reportError(f"Error sampling raster values with LFTools: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(3)
        if feedback.isCanceled(): return {}

        # ETAPA 4: Processar valores Z do DEM
        feedback.pushInfo("STEP 4: Processing DEM Z-values...")
        temp_file_z = os.path.join(tempfile.gettempdir(), f'pontos_z_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_z)
        if os.path.exists(temp_file_z): os.remove(temp_file_z)
        try:
            extracted_points = QgsVectorLayer(temp_file_amostrado, 'extracted_points', 'ogr')
            if not extracted_points.isValid():
                feedback.reportError("Invalid sampled point layer")
                return {}
            field_names = [field.name() for field in extracted_points.fields()]
            sample_band_name = 'sample_band_1'
            if sample_band_name not in field_names:
                feedback.reportError("Field 'sample_band_1' not found in layer")
                return {}
            outputs['DefinirValorZ'] = processing.run("native:setzvalue", {
                'INPUT': extracted_points,
                'Z_VALUE': QgsProperty.fromExpression(f'"{sample_band_name}"'),
                'OUTPUT': temp_file_z
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Z values processed successfully")
        except Exception as e:
            feedback.reportError(f"Error processing Z values: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(4)
        if feedback.isCanceled(): return {}

        # ETAPA 5: Reprojetar para CRS projetado
        feedback.pushInfo("STEP 5: Reprojecting layer...")
        temp_file_reprojetada = os.path.join(tempfile.gettempdir(), f'camada_reprojetada_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_reprojetada)
        if os.path.exists(temp_file_reprojetada): os.remove(temp_file_reprojetada)
        try:
            outputs['ReprojetarCamada'] = processing.run('native:reprojectlayer', {
                'INPUT': temp_file_z, 'TARGET_CRS': parameters['src_projetado'], 'OUTPUT': temp_file_reprojetada
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Layer successfully reprojected")
        except Exception as e:
            feedback.reportError(f"Error reprojecting layer: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(5)
        if feedback.isCanceled(): return {}

        # ETAPA 6: Calcular distância mínima entre pontos
        feedback.pushInfo("STEP 6: Calculating minimum distance between points...")
        try:
            pontos_reprojetados = QgsVectorLayer(temp_file_reprojetada, 'pontos_reprojetados', 'ogr')
            features = list(pontos_reprojetados.getFeatures())
            distancias = []
            for i in range(len(features) - 1):
                pt1 = features[i].geometry().asPoint()
                pt2 = features[i + 1].geometry().asPoint()
                dist = ((pt1.x() - pt2.x())**2 + (pt1.y() - pt2.y())**2) ** 0.5
                if dist > 0.01:
                    distancias.append(dist)
            if distancias:
                distancia_minima = min(distancias)
                raio_buffer = distancia_minima / 2
                feedback.pushInfo(f"\u2713 Minimum distance: {distancia_minima:.2f} m  Buffer radius: {raio_buffer:.2f} m")
            else:
                raio_buffer = 5
                feedback.pushInfo("\u26a0 Using default buffer radius")
        except Exception as e:
            raio_buffer = 5
            feedback.pushInfo(f"\u26a0 Error calculating distance: {str(e)}, using default")

        feedback.setCurrentStep(6)
        if feedback.isCanceled(): return {}

        # ETAPA 7: Pontos para linhas
        feedback.pushInfo("STEP 7: Converting points to lines...")
        temp_file_linha = os.path.join(tempfile.gettempdir(), f'linha_trajetoria_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_linha)
        if os.path.exists(temp_file_linha): os.remove(temp_file_linha)
        try:
            outputs['PontosParaLinhas'] = processing.run('native:pointstopath', {
                'INPUT': temp_file_reprojetada, 'ORDER_EXPRESSION': '"original_index"', 'OUTPUT': temp_file_linha
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Points successfully converted to lines")

            if parameters['adicionar_linha_trajetoria']:
                linha_layer = QgsVectorLayer(temp_file_linha, 'linha_trajetoria', 'ogr')
                if linha_layer.isValid():
                    csv_name = os.path.splitext(os.path.basename(csv_path))[0]
                    linha_layer.setName(f"path - {csv_name}_Simp")
                    line_symbol = QgsLineSymbol.createSimple({'color': 'blue', 'width': '0.3'})
                    seta = QgsMarkerSymbol.createSimple({'name': 'arrow', 'size': '5', 'color': 'blue', 'angle': '90'})
                    marcador = QgsMarkerLineSymbolLayer()
                    marcador.setInterval(30)
                    marcador.setSubSymbol(seta)
                    line_symbol.appendSymbolLayer(marcador)
                    linha_layer.setRenderer(QgsSingleSymbolRenderer(line_symbol))
                    QgsProject.instance().addMapLayer(linha_layer)
                    feedback.pushInfo("\u2713 Trajectory line layer added to project")
        except Exception as e:
            feedback.reportError(f"Error converting points to line: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(7)
        if feedback.isCanceled(): return {}

        # ETAPA 8: Simplificar linha
        feedback.pushInfo("STEP 8: Simplifying line...")
        temp_file_simplificada = os.path.join(tempfile.gettempdir(), f'linha_simplificada_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_simplificada)
        if os.path.exists(temp_file_simplificada): os.remove(temp_file_simplificada)
        try:
            outputs['Simplificar'] = processing.run('native:simplifygeometries', {
                'INPUT': temp_file_linha, 'METHOD': 2, 'TOLERANCE': parameters['tolerancia'], 'OUTPUT': temp_file_simplificada
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Line successfully simplified")
        except Exception as e:
            feedback.reportError(f"Error simplifying line: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(8)
        if feedback.isCanceled(): return {}

        # ETAPA 9: Extrair vértices
        feedback.pushInfo("STEP 9: Extracting vertices...")
        temp_file_vertices = os.path.join(tempfile.gettempdir(), f'vertices_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_vertices)
        if os.path.exists(temp_file_vertices): os.remove(temp_file_vertices)
        try:
            outputs['ExtrairVertices'] = processing.run('native:extractvertices', {
                'INPUT': temp_file_simplificada, 'OUTPUT': temp_file_vertices
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Vertices extracted successfully")
        except Exception as e:
            feedback.reportError(f"Error extracting vertices: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(9)
        if feedback.isCanceled(): return {}

        # ETAPA 10: Criar buffers
        feedback.pushInfo("STEP 10: Creating buffers around vertices...")
        temp_file_buffers = os.path.join(tempfile.gettempdir(), f'buffers_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_buffers)
        if os.path.exists(temp_file_buffers): os.remove(temp_file_buffers)
        try:
            outputs['CriarBuffers'] = processing.run('native:buffer', {
                'DISSOLVE': False, 'DISTANCE': raio_buffer, 'END_CAP_STYLE': 0,
                'INPUT': temp_file_vertices, 'JOIN_STYLE': 0, 'MITER_LIMIT': 2,
                'SEGMENTS': 5, 'OUTPUT': temp_file_buffers
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Buffers created successfully")
        except Exception as e:
            feedback.reportError(f"Error creating buffers: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(10)
        if feedback.isCanceled(): return {}

        # ETAPA 11: Unir atributos por localização
        feedback.pushInfo("STEP 11: Merging attributes by location...")
        temp_file_atributos_unidos = os.path.join(tempfile.gettempdir(), f'atributos_unidos_{uuid.uuid4().hex}.gpkg')
        temp_files.append(temp_file_atributos_unidos)
        if os.path.exists(temp_file_atributos_unidos): os.remove(temp_file_atributos_unidos)
        try:
            outputs['UnirAtributos'] = processing.run('native:joinattributesbylocation', {
                'DISCARD_NONMATCHING': True,
                'INPUT': temp_file_reprojetada,
                'JOIN': temp_file_buffers,
                'PREDICATE': [0],
                'OUTPUT': temp_file_atributos_unidos
            }, context=context, feedback=feedback, is_child_algorithm=True)
            feedback.pushInfo("\u2713 Attributes successfully merged")
        except Exception as e:
            feedback.reportError(f"Error merging attributes: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(11)
        if feedback.isCanceled(): return {}

        # ETAPA 12: Extrair índices dos pontos simplificados
        feedback.pushInfo("STEP 12: Extracting simplified indexes...")
        try:
            simplified_layer = QgsVectorLayer(temp_file_atributos_unidos, 'simplified_layer', 'ogr')
            if not simplified_layer or not simplified_layer.isValid():
                feedback.reportError("Unable to load simplified layer")
                return {}

            field_names = [f.name() for f in simplified_layer.fields()]
            if 'original_index' not in field_names:
                feedback.reportError("Field 'original_index' not found in simplified layer")
                return {}

            indices_simplificados = set()
            feature_count = 0
            for feature in simplified_layer.getFeatures():
                index = feature.attribute('original_index')
                if index is not None:
                    indices_simplificados.add(int(index))
                feature_count += 1

            feedback.pushInfo(f"\u2713 Processed {feature_count} features, found {len(indices_simplificados)} simplified indices")

        except Exception as e:
            feedback.reportError(f"Error extracting indexes: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        feedback.setCurrentStep(12)
        if feedback.isCanceled(): return {}

        # ETAPA 13: Filtrar CSV original com base nos índices
        feedback.pushInfo("STEP 13: Filtering original CSV...")
        try:
            csv_path = self.parameterAsString(parameters, 'voo_em_csv', context)
            csv_saida = self.parameterAsString(parameters, 'csv_saida', context)

            with open(csv_path, 'r', encoding='utf-8') as f_in:
                leitor = csv.reader(f_in)
                cabecalho = next(leitor)
                linhas = list(leitor)

            with open(csv_saida, 'w', newline='', encoding='utf-8') as f_out:
                escritor = csv.writer(f_out)
                escritor.writerow(cabecalho)
                for idx, linha in enumerate(linhas, start=1):
                    if idx in indices_simplificados:
                        escritor.writerow(linha)

            feedback.pushInfo(f"\u2713 Simplified CSV saved in: {csv_saida}")
            results['CSV_Simplificado'] = csv_saida

            # Adicionar camada de pontos simplificados APÓS CSV gerado
            if parameters['adicionar_pontos_simplificados']:
                csv_name = os.path.splitext(os.path.basename(csv_saida))[0]
                simp_layer = csv_como_layer(csv_saida, layer_name=csv_name)
                if simp_layer and simp_layer.isValid():
                    QgsProject.instance().addMapLayer(simp_layer)
                    try:
                        processing.run("lftools:magicstyles", {'LAYER': simp_layer, 'STYLE_POINT': 1})
                    except:
                        pass
                    feedback.pushInfo("\u2713 Simplified points layer added to project")

        except Exception as e:
            feedback.reportError(f"Error filtering CSV: {str(e)}")
            for f in temp_files:
                if os.path.exists(f): os.remove(f)
            return {}

        # Limpar arquivos temporários
        for f in temp_files:
            try:
                if os.path.exists(f): os.remove(f)
            except: pass

        feedback.pushInfo("=" * 50)
        feedback.pushInfo("PROCESSING COMPLETED SUCCESSFULLY!")
        feedback.pushInfo("=" * 50)

        return results

    def name(self):
        return 'SimplifyWaypoints'.lower()

    def displayName(self):
        return self.tr('1. Simplify Waypoints')

    def group(self):
        return 'CSV Tools'

    def groupId(self):
        return 'CSVTools'.lower()

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CSV_Simplify()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drones,GeoOne,simplify,simplificar,generalize').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/CSV.png'))

    figura2 = 'images/csv_simplipy.jpg'

    def shortHelpString(self):
        texto = f"""
        <p>This tool optimizes the flight plan by reducing the number of waypoints through a three-dimensional tolerance relative to the original flight line.</p>
        <p>It generates a new <b>CSV</b> with simplified flight plan compatible with the <b>Litchi</b> app.</p>
        """
        corpo = '''<div align="center">
                      <img src="''' + os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura2) + '''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b></p>
                        <ul>
                            <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a></li>
                            <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6025">Click here to access the class with all the details about this tool!</a></li>
                        </ul>
                      <p align="right"><b>Autores: Prof Cazaroli, Leandro França and Ilton Freitas</b></p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,''' + GeoOne + '''"></a>
                      <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>'''
        return self.tr(texto) + corpo
