# -*- coding: utf-8 -*-

"""
/***************************************************************************
 GeoFlight Planner - Functions
                                 A QGIS plugin
 GeoFlight Planner - Functions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-02
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2024-12-02'
__copyright__ = '(C) 2024 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
import os
from qgis.PyQt.QtGui import QColor, QFont
from qgis.PyQt.QtCore import QVariant
import qgis.utils
import numpy as np
import csv

def gerar_CSV(flight_type, pontos_fotos, arquivo_csv, velocidade, tempo, delta, angulo, H, gimbalAng, terrain=None, deltaFront_op=None):
   # Criar o arquivo CSV do Litchi
   with open(arquivo_csv, mode='w', newline='') as csvfile:
         # Definir os cabeçalhos do arquivo CSV
         fieldnames = [
               "latitude", "longitude", "altitude(m)",
               "heading(deg)", "curvesize(m)", "rotationdir",
               "gimbalmode", "gimbalpitchangle",
               "actiontype1", "actionparam1", "actiontype2", "actionparam2",
               "actiontype3", "actionparam3", "actiontype4", "actionparam4",
               "actiontype5", "actionparam5", "actiontype6", "actionparam6",
               "actiontype7", "actionparam7", "actiontype8", "actionparam8",
               "actiontype9", "actionparam9", "actiontype10", "actionparam10",
               "actiontype11", "actionparam11", "actiontype12", "actionparam12",
               "actiontype13", "actionparam13", "actiontype14", "actionparam14",
               "actiontype15", "actionparam15", "altitudemode", "speed(m/s)",
               "poi_latitude", "poi_longitude", "poi_altitude(m)", "poi_altitudemode",
               "photo_timeinterval", "photo_distinterval"]

         writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
         writer.writeheader()

         alturavoo    = H
         angulo_gimbal = gimbalAng
         above_ground = 1 if terrain else 0
         mode_gimbal  = 2 if flight_type in ("H", "S", "L") else 0

         if flight_type == "H_RC2":
            t1, t2, t3, t4        = -1, 0, -1, 0
            time_interval         = -1
            dist_interval         = -1
         else:
            t1, t2, t3, t4        = (1, 0, -1, 0) if tempo == 0 else (0, tempo * 1000, 1, 0)
            time_interval         = delta if deltaFront_op == 1 else -1
            dist_interval         = -1    if deltaFront_op == 1 else delta
         
         for ponto in pontos_fotos:
            longitude = ponto['longitude']
            latitude = ponto['latitude']

            if flight_type == "VF" or flight_type == "VC":
               alturavoo = ponto['height']
               angulo = ponto['bowangle']
            elif flight_type in ("L", "H_RC2"):
               angulo = ponto['bowangle']

            data = {
               "latitude": f"{latitude:.8f}",
               "longitude": f"{longitude:.8f}",
               "altitude(m)": f"{alturavoo:.1f}",
               "heading(deg)": f"{angulo:.0f}",
               "curvesize(m)": 0,
               "rotationdir": 0,
               "gimbalmode": mode_gimbal,
               "gimbalpitchangle": angulo_gimbal,
               "actiontype1": t1,
               "actionparam1": t2,
               "actiontype2": t3,
               "actionparam2": t4,
               "actiontype3": -1, "actionparam3": 0,
               "actiontype4": -1, "actionparam4": 0,
               "actiontype5": -1, "actionparam5": 0,
               "actiontype6": -1, "actionparam6": 0,
               "actiontype7": -1, "actionparam7": 0,
               "actiontype8": -1, "actionparam8": 0,
               "actiontype9": -1, "actionparam9": 0,
               "actiontype10": -1, "actionparam10": 0,
               "actiontype11": -1, "actionparam11": 0,
               "actiontype12": -1, "actionparam12": 0,
               "actiontype13": -1, "actionparam13": 0,
               "actiontype14": -1, "actionparam14": 0,
               "actiontype15": -1, "actionparam15": 0,
               "altitudemode": above_ground,
               "speed(m/s)": velocidade,
               "poi_latitude": 0,
               "poi_longitude": 0,
               "poi_altitude(m)": 0,
               "poi_altitudemode": 0,
               "photo_timeinterval": time_interval,
               "photo_distinterval": f"{dist_interval:.2f}"}
            writer.writerow(data)

def verificar_plugins(plugins_list, feedback=None):
    # Obter a lista de todos os plugins instalados
    installed_plugins = qgis.utils.plugins.keys()

    plugins_not_installed = [plugin for plugin in plugins_list if plugin not in installed_plugins]

    # Se houver plugins não instalados, levantar erro
    if plugins_not_installed:
       raise Exception(f"❌ The following plugins are not installed: {', '.join(plugins_not_installed)}")
    else:
       feedback.pushInfo(f"✅ All plugins are installed: {plugins_list}")

    return

def saveParametros(tipoVoo, pontoInicial=None, h=None, dist=None, gimbal=None, csv=None, 
                   v=None, t=None, abGround=None, dl=None, df=None, dfop=None,
                   altMin=None, anguloFotoVC=None, dVertVC=None, csvI=None, crs=None, 
                   tol=None, add1=None, add2=None, add3=None):
    s = QgsSettings()
    prefixo = "qgis-drone-flight-planner/"

    if tipoVoo == "H_Sensor":
        s.setValue(prefixo + "hVooS", h)
        s.setValue(prefixo + "abGroundS", abGround)
        s.setValue(prefixo + "dlS", dl)
        s.setValue(prefixo + "dfS", df)
        s.setValue(prefixo + "velocS", v)
        s.setValue(prefixo + "tStayS", t)
        s.setValue(prefixo + "gimbalS", gimbal)
        s.setValue(prefixo + "csvS", csv)

    elif tipoVoo == "H_Manual":
        s.setValue(prefixo + "hVooM", h)
        s.setValue(prefixo + "abGroundM", abGround)
        s.setValue(prefixo + "dlM", dl)
        s.setValue(prefixo + "dfopM", dfop)
        s.setValue(prefixo + "dfM", df)
        s.setValue(prefixo + "velocM", v)
        s.setValue(prefixo + "tStayM", t)
        s.setValue(prefixo + "gimbalM", gimbal)
        s.setValue(prefixo + "csvM", csv)

    elif tipoVoo == "H_Manual_RC2_Controller":
        s.setValue(prefixo + "hVooRC2", h)
        s.setValue(prefixo + "abGroundRC2", abGround)
        s.setValue(prefixo + "dlRC2", dl)
        s.setValue(prefixo + "gimbalRC2", gimbal)
        s.setValue(prefixo + "csvRC2", csv)

    elif tipoVoo == "H_Line":
        s.setValue(prefixo + "hVooL", h)
        s.setValue(prefixo + "abGroundL", abGround)
        s.setValue(prefixo + "dlL", dl)
        s.setValue(prefixo + "nLinL", dfop)
        s.setValue(prefixo + "dfL", df)
        s.setValue(prefixo + "velocL", v)
        s.setValue(prefixo + "tStayL", t)
        s.setValue(prefixo + "gimbalL", gimbal)
        s.setValue(prefixo + "csvL", csv)

    elif tipoVoo == "VF":
        s.setValue(prefixo + "distVF", dist)
        s.setValue(prefixo + "hObjVF", h)
        s.setValue(prefixo + "altMinVF", altMin)
        s.setValue(prefixo + "dlVF", dl)
        s.setValue(prefixo + "dfVF", df)
        s.setValue(prefixo + "velocVF", v)
        s.setValue(prefixo + "tStayVF", t)
        s.setValue(prefixo + "gimbalVF", gimbal)
        s.setValue(prefixo + "csvVF", csv)

    elif tipoVoo == "VC":
        s.setValue(prefixo + "pontoInicialVC", pontoInicial)
        s.setValue(prefixo + "hObjVC", h)
        s.setValue(prefixo + "altMinVC", altMin)
        s.setValue(prefixo + "anguloFotoVC", anguloFotoVC)
        s.setValue(prefixo + "dVertVC", dVertVC)
        s.setValue(prefixo + "velocVC", v)
        s.setValue(prefixo + "tStayVC", t)
        s.setValue(prefixo + "gimbalVC", gimbal)
        s.setValue(prefixo + "csvVC", csv)

    elif tipoVoo == "H_Simplified":
        s.setValue(prefixo + "csvInSimplified", csvI)
        s.setValue(prefixo + "csvOutSimplified", csv)
        s.setValue(prefixo + "CRSSimplified", crs)
        s.setValue(prefixo + "toleranceSimplified", tol)
        s.setValue(prefixo + "addPCsvSimplified", add1)
        s.setValue(prefixo + "addPSimplified", add2)
        s.setValue(prefixo + "addLSimplified", add3)

    elif tipoVoo == "H_Merge":
        s.setValue(prefixo + "csv1Merge", csvI)
        s.setValue(prefixo + "csv2Merge", csv)
        s.setValue(prefixo + "addCsvMerge", add1)
        s.setValue(prefixo + "addPointsMerge", add2)

def loadParametros(tipoVoo):
    s = QgsSettings()
    prefixo = "qgis-drone-flight-planner/"

    if tipoVoo == "H_Sensor":
        return (
            s.value(prefixo + "hVooS", 100),
            s.value(prefixo + "abGroundS", True),
            s.value(prefixo + "dlS", 0.75),
            s.value(prefixo + "dfS", 0.85),
            s.value(prefixo + "velocS", 8),
            s.value(prefixo + "tStayS", 0),
            s.value(prefixo + "gimbalS", -90),
            s.value(prefixo + "csvS", "")
        )

    elif tipoVoo == "H_Manual":
        return (
            s.value(prefixo + "hVooM", 100),
            s.value(prefixo + "abGroundM", True),
            s.value(prefixo + "dlM", 10),
            s.value(prefixo + "dfopM", 0),
            s.value(prefixo + "dfM", 10),
            s.value(prefixo + "velocM", 8),
            s.value(prefixo + "tStayM", 0),
            s.value(prefixo + "gimbalM", -90),
            s.value(prefixo + "csvM", "")
        )

    elif tipoVoo == "H_Manual_RC2_Controller":
        return (
            s.value(prefixo + "hVooRC2", 100),
            s.value(prefixo + "abGroundRC2", True),
            s.value(prefixo + "dlRC2", 10),
            s.value(prefixo + "gimbalRC2", -90),
            s.value(prefixo + "csvRC2", "")
        )
    
    elif tipoVoo == "H_Line":
        return (
            s.value(prefixo + "hVooL", 100),
            s.value(prefixo + "abGroundL", True),
            s.value(prefixo + "dlL", 10),
            s.value(prefixo + "nLinL", 2),
            s.value(prefixo + "dfL", 10),
            s.value(prefixo + "velocL", 8),
            s.value(prefixo + "tStayL", 0),
            s.value(prefixo + "gimbalL", -90),
            s.value(prefixo + "csvL", "")
        )

    elif tipoVoo == "VF":
        return (
            s.value(prefixo + "distVF", 10),
            s.value(prefixo + "hObjVF", 15),
            s.value(prefixo + "altMinVF", 2.5),
            s.value(prefixo + "dlVF", 5),
            s.value(prefixo + "dfVF", 3),
            s.value(prefixo + "velocVF", 1),
            s.value(prefixo + "tStayVF", 2),
            s.value(prefixo + "gimbalVF", 0),
            s.value(prefixo + "csvVF", "")
        )

    elif tipoVoo == "VC":
        return (
            s.value(prefixo + "pontoInicialVC", 0),
            s.value(prefixo + "hObjVC", 15),
            s.value(prefixo + "altMinVC", 2.5),
            s.value(prefixo + "anguloFotoVC", 30),
            s.value(prefixo + "dVertVC", 3),
            s.value(prefixo + "velocVC", 1),
            s.value(prefixo + "tStayVC", 2),
            s.value(prefixo + "gimbalVC", 0),
            s.value(prefixo + "csvVC", "")
        )
    
    elif tipoVoo == "H_Simplified":
        return (
            s.value(prefixo + "csvInSimplified", ""),
            s.value(prefixo + "csvOutSimplified", ""),
            s.value(prefixo + "toleranceSimplified", 15.0),
            s.value(prefixo + "addPCsvSimplified", False),
            s.value(prefixo + "addPSimplified", False),
            s.value(prefixo + "addLSimplified", False)
        )
    
    elif tipoVoo == "H_Merge":
        return (
            s.value(prefixo + "csv1Merge", ""),
            s.value(prefixo + "csv2Merge", ""),
            s.value(prefixo + "addCsvMerge", ""),
            s.value(prefixo + "addPointsMerge", False)
        )

def meters2degrees(dist, lat, SRC): # Transformar distancia em metros para graus
    ellipsoid_id = SRC.ellipsoidAcronym()
    ellipsoid = QgsEllipsoidUtils.ellipsoidParameters(ellipsoid_id)
    a = ellipsoid.semiMajor
    f_inv = ellipsoid.inverseFlattening
    f = 1/f_inv
    e2 = f*(2-f)
    N = a/np.sqrt(1-e2*(np.sin(lat))**2)
    M = a*(1-e2)/(1-e2*(np.sin(lat))**2)**(3/2.)
    R = np.sqrt(M*N)
    theta = dist/R

    return np.degrees(theta)

def azimute(A, B): # Cálculo dos azimutes entre dois pontos (vetor AB: origem A, extremidade B)
    dx = B.x() - A.x()
    dy = B.y() - A.y()

    # Pontos coincidentes
    if dx == 0 and dy == 0:
        return None, None

    # Azimute a partir do Norte, no sentido horário
    AzAB = np.arctan2(dx, dy) % (2 * np.pi)
    AzBA = (AzAB + np.pi) % (2 * np.pi)

    return AzAB, AzBA

def distancia(P1, P2):
    """Distância euclidiana entre dois QgsPointXY."""
    return np.sqrt((P1.x() - P2.x())**2 + (P1.y() - P2.y())**2)

def pontos_na_linha(geom_linha, deltaFront_graus, altVoo, azimute_func):
    """
    Gera lista de dicts {longitude, latitude, height, bowangle} distribuídos
    ao longo de geom_linha (QgsGeometry LineString em graus WGS84),
    com espaçamento deltaFront_graus entre pontos.

    Parâmetros:
        geom_linha       : QgsGeometry (LineString ou MultiLineString, WGS84)
        deltaFront_graus : float — espaçamento entre fotos em graus
        altVoo           : float — altura de voo em metros
        azimute_func     : callable — função azimute(A, B) -> (AzAB, AzBA)
    """
    if geom_linha.isMultipart():
        coord = geom_linha.asMultiPolyline()[0]
    else:
        coord = geom_linha.asPolyline()

    comprimento = geom_linha.length()

    # Distâncias acumuladas nos vértices
    ListaDist = [0]
    soma = 0.0
    for i in range(len(coord) - 1):
        soma += distancia(coord[i], coord[i + 1])
        ListaDist.append(soma)

    # Número de seções e espaçamento ajustado
    if deltaFront_graus < comprimento:
        NumSec = int(np.floor(comprimento / deltaFront_graus))
        DistSec = comprimento / NumSec
    else:
        NumSec, DistSec = 1, comprimento

    dist_alvo = np.arange(0, comprimento + DistSec, DistSec)

    pontos = []
    cont = 0
    for k in range(len(coord) - 1):
        while cont <= NumSec and ListaDist[k] <= dist_alvo[cont] < ListaDist[k + 1]:
            p1 = np.array([coord[k].x(),     coord[k].y()])
            p2 = np.array([coord[k + 1].x(), coord[k + 1].y()])
            vetor = p2 - p1
            vetor /= np.linalg.norm(vetor)
            centro = p1 + vetor * (dist_alvo[cont] - ListaDist[k])
            Az = azimute_func(
                    QgsPointXY(float(centro[0] + vetor[1] / 2), float(centro[1] - vetor[0] / 2)),
                    QgsPointXY(float(centro[0] - vetor[1] / 2), float(centro[1] + vetor[0] / 2))
                )[1] * 180 / np.pi
            pontos.append({
                'longitude': float(centro[0]),
                'latitude':  float(centro[1]),
                'height':    altVoo,
                'bowangle':  int(Az)
            })
            cont += 1

    # Último ponto no vértice final da linha
    p1 = np.array([coord[-2].x(), coord[-2].y()])
    p2 = np.array([coord[-1].x(), coord[-1].y()])
    vetor = p2 - p1
    vetor /= np.linalg.norm(vetor)
    centro = np.array([coord[-1].x(), coord[-1].y()])
    Az = azimute_func(
        QgsPointXY(float(centro[0] + vetor[1] / 2), float(centro[1] - vetor[0] / 2)),
        QgsPointXY(float(centro[0] - vetor[1] / 2), float(centro[1] + vetor[0] / 2))
    )[1] * 180 / np.pi
    pontos.append({
        'longitude': float(centro[0]),
        'latitude':  float(centro[1]),
        'height':    altVoo,
        'bowangle':  int(Az)
    })

    return pontos

def linhas_voo_poligono(linha_ref_geom, poligono_geom, pol_pts, p1, deltaLat):
    """
    Gera linhas de voo paralelas que preenchem o polígono.

    Regra SEMPRE garantida:
      - Primeira linha: sobre o lado do polígono onde P1 está
      - Última linha:   sobre o lado oposto do polígono
      - Entre elas:     linhas espaçadas por deltaLat (0 ou mais)

    Parâmetros:
        linha_ref_geom : QgsGeometry — linha de referência (direção das linhas de voo)
        poligono_geom  : QgsGeometry — polígono da área (já em WGS84)
        pol_pts        : list de pontos — vértices do polígono
        p1             : QgsPointXY — ponto SOBRE o lado do polígono (início do voo)
        deltaLat       : float — espaçamento lateral entre linhas (em graus)
    """
    import math

    # ── Vetor da direção das linhas de voo ────────────────────────────────────
    pts_ref = linha_ref_geom.asPolyline()
    dx = pts_ref[-1].x() - pts_ref[0].x()
    dy = pts_ref[-1].y() - pts_ref[0].y()
    comp = math.sqrt(dx**2 + dy**2)
    if comp == 0:
        return []
    vx = dx / comp   # versor ao longo das linhas de voo
    vy = dy / comp
    nx = -vy         # versor perpendicular (direção de varredura)
    ny =  vx

    # ── Projeções nos dois eixos ──────────────────────────────────────────────
    proj_p1_perp  = p1.x() * nx + p1.y() * ny
    proj_p1_along = p1.x() * vx + p1.y() * vy

    proj_perp_verts  = [QgsPointXY(pt).x() * nx + QgsPointXY(pt).y() * ny for pt in pol_pts]
    proj_along_verts = [QgsPointXY(pt).x() * vx + QgsPointXY(pt).y() * vy for pt in pol_pts]

    min_along = min(proj_along_verts)
    max_along = max(proj_along_verts)
    ext = max_along - min_along  # extensão para garantir cobertura total ao longo

    # ── Direção do interior: centróide do polígono ────────────────────────────
    centroide = poligono_geom.centroid().asPoint()
    proj_centro_perp = centroide.x() * nx + centroide.y() * ny
    sinal_interior = 1 if proj_centro_perp > proj_p1_perp else -1

    # ── Distância até o lado oposto ───────────────────────────────────────────
    # Vértice mais distante de p1 na direção do interior
    dist_max_interior = max(
        (v - proj_p1_perp) * sinal_interior
        for v in proj_perp_verts
    )

    # ── Montar lista de offsets: SEMPRE primeiro e último sobre as bordas ─────
    EPSILON = deltaLat * 0.02   # distância mínima da borda para evitar vértice degenerado

    offsets = []
    offsets.append(EPSILON)                          # primeira linha: sobre a borda de P1
    offset = deltaLat
    while offset < dist_max_interior - EPSILON:      # linhas interiores
        offsets.append(offset)
        offset += deltaLat
    offsets.append(dist_max_interior - EPSILON)      # última linha: sobre a borda oposta

    # Remover duplicatas próximas (quando deltaLat > largura do polígono)
    offsets_limpos = [offsets[0]]
    for o in offsets[1:]:
        if o - offsets_limpos[-1] > EPSILON:
            offsets_limpos.append(o)

    # ── Cortar com o polígono e normalizar ────────────────────────────────────
    def clipar(geom_off):
        geom_clip = geom_off.intersection(poligono_geom)
        if not geom_clip or geom_clip.isEmpty():
            return None
        if geom_clip.isMultipart():
            partes = geom_clip.asMultiPolyline()
            if not partes:
                return None
            geom_clip = QgsGeometry.fromPolylineXY(max(partes, key=len))
        return geom_clip

    # ── Gerar linhas ──────────────────────────────────────────────────────────
    linhas_orientadas = []

    for offset in offsets_limpos:
        perp_pos = proj_p1_perp + sinal_interior * offset

        cx = nx * perp_pos
        cy = ny * perp_pos

        p_a = QgsPointXY(cx + vx * (min_along - ext), cy + vy * (min_along - ext))
        p_b = QgsPointXY(cx + vx * (max_along + ext), cy + vy * (max_along + ext))

        geom_clip = clipar(QgsGeometry.fromPolylineXY([p_a, p_b]))
        if geom_clip:
            pts = geom_clip.asMultiPolyline()[0] if geom_clip.isMultipart() else geom_clip.asPolyline()
            if pts:
                # Orientar: extremo mais próximo de P1 é o início
                proj_ini = pts[0].x()  * vx + pts[0].y()  * vy
                proj_fim = pts[-1].x() * vx + pts[-1].y() * vy
                if abs(proj_fim - proj_p1_along) < abs(proj_ini - proj_p1_along):
                    pts = list(reversed(pts))
                linhas_orientadas.append(QgsGeometry.fromPolylineXY(pts))

    return linhas_orientadas

def pontos_conexao(p_fim, p_ini, altVoo):
    """Coloca um ponto de foto no meio de cada segmento de conexao entre linhas.
    Nao inclui p_fim nem p_ini (ja estao em LISTA_PONTOS).
    """
    return [{
        'longitude': (p_fim['longitude'] + p_ini['longitude']) / 2,
        'latitude':  (p_fim['latitude']  + p_ini['latitude'])  / 2,
        'height':    altVoo,
        'bowangle':  0,
        'foto': False
    }]

def heading_para_proximo(LISTA_PONTOS, azimute_func):
    """
    Atualiza o campo 'bowangle' de cada ponto em LISTA_PONTOS para apontar
    para o próximo waypoint (ordem final da serpentina).
    O último ponto herda o heading do penúltimo.
    """
    ultimo_az = 0
    for i in range(len(LISTA_PONTOS) - 1):
        AzAB, _ = azimute_func(
            QgsPointXY(LISTA_PONTOS[i]['longitude'],     LISTA_PONTOS[i]['latitude']),
            QgsPointXY(LISTA_PONTOS[i + 1]['longitude'], LISTA_PONTOS[i + 1]['latitude'])
        )
        if AzAB is not None:
            ultimo_az = int(AzAB * 180 / np.pi)
        LISTA_PONTOS[i]['bowangle'] = ultimo_az
    if LISTA_PONTOS:
        LISTA_PONTOS[-1]['bowangle'] = ultimo_az

def salvar_kml(caminho_saida, LISTA_PONTOS, nome_doc="flight_plan.kml"):
    coords_linha = " ".join(
        f"{p['longitude']},{p['latitude']},{p['height']}"
        for p in LISTA_PONTOS
    )

    placemarks = []
    for i, p in enumerate(LISTA_PONTOS, start=1):
        placemarks.append(f"""
        <Placemark id="waypoints.{i}">
            <Point>
                <altitudeMode>relativeToGround</altitudeMode>
                <coordinates>{p['longitude']},{p['latitude']},{p['height']}</coordinates>
            </Point>
        </Placemark>""")

    kml = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
    <Document id="root_doc">
        <name>{nome_doc}</name>
        <Style id="default">
            <LineStyle>
                <color>ff0000ff</color>
                <width>2</width>
            </LineStyle>
        </Style>
        <StyleMap id="default0">
            <Pair>
                <key>normal</key>
                <styleUrl>#default</styleUrl>
            </Pair>
            <Pair>
                <key>highlight</key>
                <styleUrl>#hl</styleUrl>
            </Pair>
        </StyleMap>
        <Style id="hl">
            <IconStyle>
                <scale>1.2</scale>
            </IconStyle>
            <LineStyle>
                <color>ff0000ff</color>
                <width>2</width>
            </LineStyle>
        </Style>
        <Folder>
            <name>path</name>
            <Placemark id="path.1">
                <styleUrl>#default0</styleUrl>
                <LineString>
                    <altitudeMode>relativeToGround</altitudeMode>
                    <coordinates>
                        {coords_linha}
                    </coordinates>
                </LineString>
            </Placemark>
        </Folder>

        <Folder>
            <name>waypoints</name>
            {''.join(placemarks)}
        </Folder>
    </Document>
</kml>
"""

    with open(caminho_saida, "w", encoding="utf-8") as f:
        f.write(kml)

def csv_como_layer(csv_path, layer_name=None, add_to_project=True):
    """
    Carrega um CSV exportado pelo plugin como camada de pontos no QGIS.
    Espera colunas latitude e longitude em EPSG:4326.
    """
    if not csv_path or not os.path.exists(csv_path):
        return None

    if layer_name is None:
        layer_name = os.path.splitext(os.path.basename(csv_path))[0]

    csv_path_uri = csv_path.replace("\\", "/")

    uri = (
        f"file:///{csv_path_uri}"
        f"?type=csv"
        f"&delimiter=,"
        f"&detectTypes=yes"
        f"&xField=longitude"
        f"&yField=latitude"
        f"&geomType=point"
        f"&crs=EPSG:4326"
    )

    layer = QgsVectorLayer(uri, 'waypoints - ' + layer_name, "delimitedtext")

    if not layer.isValid():
        return None

    return layer

def criar_layer_path(LISTA_PONTOS, arquivo_csv):
    """Cria camada de linhas de voo na direção correta da serpentina,
    quebrando nos pontos de conexão (foto=False)."""
    nome_path = 'path - ' + os.path.splitext(os.path.basename(arquivo_csv))[0]
    layer_path = QgsVectorLayer('LineString?crs=EPSG:4326', nome_path, 'memory')
    prov_path = layer_path.dataProvider()
    prov_path.addAttributes([QgsField('id', QVariant.Int)])
    layer_path.updateFields()

    # Quebrar nos pontos de conexão (foto=False) — cada linha de voo vira uma feature
    segmentos = []
    seg = []
    for ponto in LISTA_PONTOS:
        eh_foto = ponto['foto'] if isinstance(ponto, dict) and 'foto' in ponto else True
        if eh_foto:
            seg.append(QgsPointXY(ponto['longitude'], ponto['latitude']))
        else:
            if len(seg) >= 2:
                segmentos.append(seg)
            seg = []
    if len(seg) >= 2:
        segmentos.append(seg)
    if not segmentos:
        segmentos = [[QgsPointXY(ponto['longitude'], ponto['latitude']) for ponto in LISTA_PONTOS]]

    feats = []
    for i, seg in enumerate(segmentos, start=1):
        feat = QgsFeature()
        feat.setGeometry(QgsGeometry.fromPolylineXY(seg))
        feat.setAttributes([i])
        feats.append(feat)
    prov_path.addFeatures(feats)
    layer_path.updateExtents()

    line_symbol = QgsLineSymbol.createSimple({'color': 'blue', 'width': '0.3'})
    seta = QgsMarkerSymbol.createSimple({'name': 'arrow', 'size': '5', 'color': 'blue', 'angle': '90'})
    marcador = QgsMarkerLineSymbolLayer()
    marcador.setInterval(30)
    marcador.setSubSymbol(seta)
    line_symbol.appendSymbolLayer(marcador)
    layer_path.setRenderer(QgsSingleSymbolRenderer(line_symbol))

    return layer_path

def montar_LISTA_PONTOS(linhas_voo, deltaFront_g, altVoo, azimute_func, p1,
                         modo='distancia'):
    """
    Monta LISTA_PONTOS em serpentina a partir das linhas de voo.

    modo='distancia' : pontos ao longo de cada linha (pontos_na_linha)
    modo='bordas'    : apenas extremidades de cada linha (RC2 / Manual por tempo)
    """
    LISTA_PONTOS = []
    direcao = 1

    for geom_linha in linhas_voo:
        if modo == 'distancia':
            pontos = pontos_na_linha(geom_linha, deltaFront_g, altVoo, azimute_func)
            pontos_linha = pontos[::direcao]
        else:  # bordas
            pts = geom_linha.asMultiPolyline()[0] if geom_linha.isMultipart() else geom_linha.asPolyline()
            if not pts:
                direcao *= -1
                continue
            if direcao == 1:
                pontos_linha = [
                    {'longitude': float(pts[0].x()),  'latitude': float(pts[0].y()),  'height': altVoo, 'bowangle': 0},
                    {'longitude': float(pts[-1].x()), 'latitude': float(pts[-1].y()), 'height': altVoo, 'bowangle': 0}
                ]
            else:
                pontos_linha = [
                    {'longitude': float(pts[-1].x()), 'latitude': float(pts[-1].y()), 'height': altVoo, 'bowangle': 0},
                    {'longitude': float(pts[0].x()),  'latitude': float(pts[0].y()),  'height': altVoo, 'bowangle': 0}
                ]

        if LISTA_PONTOS and pontos_linha:
            LISTA_PONTOS.extend(pontos_conexao(LISTA_PONTOS[-1], pontos_linha[0], altVoo))
        LISTA_PONTOS.extend(pontos_linha)
        direcao *= -1

    # Garantir que o voo começa pelo lado de p1
    # Usa o primeiro ponto da primeira linha de voo como referência
    # (mais confiável que p1 quando a linha de ref não está sobre a borda)
    if LISTA_PONTOS and linhas_voo:
        primeira_linha = linhas_voo[0]
        pts_ref = primeira_linha.asMultiPolyline()[0] if primeira_linha.isMultipart() else primeira_linha.asPolyline()
        if pts_ref:
            ref = QgsPointXY(pts_ref[0])  # extremo inicial da primeira linha de voo
            d_ini = (LISTA_PONTOS[0]['longitude']  - ref.x())**2 + (LISTA_PONTOS[0]['latitude']  - ref.y())**2
            d_fim = (LISTA_PONTOS[-1]['longitude'] - ref.x())**2 + (LISTA_PONTOS[-1]['latitude'] - ref.y())**2
            if d_fim < d_ini:
                LISTA_PONTOS.reverse()

    return LISTA_PONTOS

def salvar_outputs(LISTA_PONTOS, arquivo_csv, flight_type, velocidade, tempo,
                   delta, angulo, altVoo, gimbalAng, terrain, deltaFront_op=None):
    """Gera CSV e KML. Retorna caminho do KML."""
    if arquivo_csv and arquivo_csv.endswith('.csv'):
        gerar_CSV(flight_type, LISTA_PONTOS, arquivo_csv, velocidade, tempo,
                  delta, angulo, altVoo, gimbalAng, terrain, deltaFront_op)

    base, _ = os.path.splitext(arquivo_csv)
    caminho_kml = base + ".kml"
    salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

    return caminho_kml

def post_process_comum(context, feedback, layer_path=None, csv_path=None,
                        kml_path=None, abrir_kml=False):
    """postProcessAlgorithm comum a todos os voos horizontais."""
    if layer_path:
        QgsProject.instance().addMapLayer(layer_path)
        feedback.pushInfo("✅ Flight path layer added to QGIS.")

    if csv_path:
        layer_pontos = csv_como_layer(csv_path, layer_name=None)
        if layer_pontos is None or not layer_pontos.isValid():
            feedback.reportError("❌ Could not load CSV as point layer.")
        else:
            QgsProject.instance().addMapLayer(layer_pontos)
            feedback.pushInfo("✅ CSV point layer added to QGIS.")
        try:
            import processing
            processing.run("lftools:magicstyles", {'LAYER': layer_pontos, 'STYLE_POINT': 1})
        except:
            feedback.reportError("💡 Install or enable the LFTools plugin to view the drone's heading.")

    if abrir_kml and kml_path and os.path.exists(kml_path):
        from qgis.PyQt.QtGui import QDesktopServices
        from qgis.PyQt.QtCore import QUrl
        ok = QDesktopServices.openUrl(QUrl.fromLocalFile(kml_path))
        if ok:
            feedback.pushInfo("✅ KML opened with the default application.")
        else:
            feedback.reportError("⚠️ Could not open the KML automatically.")

