# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Vertical Flight Non-Linear Facade
                                 A QGIS plugin
 Flight Planner VnoLF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-02
        copyright            : (C) 2026 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2026-03-02'
__copyright__ = '(C) 2026 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from ..images.Imgs import *
import processing
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    set_Z_value,
    reprojeta_camada_WGS84,
    pontos3D,
    simbologiaPontos,
    simbologiaPontos3D,
    verificarCRS,
    loadParametros,
    saveParametros,
    calculaDistancia_Linha_Ponto,
    removeLayersReproj
)

class PlanoVoo_V_noLF(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        distVnoLF, hObjVnoLF, altMinVnoLF, dlVnoLF, dfVnoLF, velocVnoLF, tStayVnoLF, gimbalVnoLF, rasterVnoLF, csvVnoLF = loadParametros("VnoLF")

        self.addParameter(QgsProcessingParameterVectorLayer('pontos_base','Position Points of the Facade', types=[QgsProcessing.TypeVectorPoint]))
        self.addParameter(QgsProcessingParameterNumber('dist','Distance from the Facade Flight Line (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=3,defaultValue=distVnoLF))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=False))
        self.addParameter(QgsProcessingParameterBoolean('inverte','Reverse Flight Start',defaultValue=False))
        self.addParameter(QgsProcessingParameterNumber('altura','Facade Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hObjVnoLF))
        self.addParameter(QgsProcessingParameterNumber('alturaMin','Start Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=altMinVnoLF))
        self.addParameter(QgsProcessingParameterNumber('dl','Spacing between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.5,defaultValue=dlVnoLF))
        self.addParameter(QgsProcessingParameterNumber('df','Spacing between Photos (m)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.5,defaultValue=dfVnoLF))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocVnoLF))
        self.addParameter(QgsProcessingParameterNumber('tempo','Wait time for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayVnoLF))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalVnoLF))
        self.addParameter(QgsProcessingParameterRasterLayer('raster','Input Raster (if any)', defaultValue=rasterVnoLF, optional=True))
        #self.addParameter(QgsProcessingParameterFolderDestination('saida_kml', 'Output Folder for kml (Google Earth)', defaultValue=skml, optional=True))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvVnoLF))

    def processAlgorithm(self, parameters, context, feedback):
        teste = False # Quando True mostra camadas intermediárias

        # ===== Parâmetros de entrada para variáveis ====================================================
        pontos_base = self.parameterAsVectorLayer(parameters, 'pontos_base', context)

        camadaMDE = self.parameterAsRasterLayer(parameters, 'raster', context)

        dist_fachada = parameters['dist']
        H = parameters['altura']
        h = parameters['alturaMin']
        terrain = parameters['aboveGround']
        inverte = parameters['inverte']
        deltaLat = parameters['dl']   # Distância das linhas de voo paralelas - sem cálculo
        deltaFront = parameters['df'] # Espaçamento Frontal entre as fotografias- sem cálculo
        velocidade = parameters['velocidade']
        tempo = parameters['tempo']
        gimbalAng = parameters['gimbalAng']
        raster_layer = self.parameterAsRasterLayer(parameters, 'raster', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)

        # ===== Verificações =============================================================================
        # Verificar se as camadas estão salvas e fora da edição
        for lyr, nome in [(pontos_base, 'Position Points of the Facade')]:
            if lyr.isEditable():
                raise QgsProcessingException(f"❌ Layer '{nome}' is in edit mode. Please save and exit editing before continuing.")
            
            # Detecta camada temporária ou não salva
            storage_type = lyr.dataProvider().storageType().lower()
            uri = lyr.dataProvider().dataSourceUri().lower()
            if storage_type == '' or 'memory:' in uri or '/temporary/' in uri:
                raise QgsProcessingException(f"❌ Layer '{nome}' is not saved. Save the layer to disk before using it.")

        # Verificar se a camada de Pontos possui mais de 3 feições pelo menos
        if pontos_base.featureCount() < 3:
             feedback.reportError("❌ At least 3 points are required.")
             return {}
         
        # Verificar caminho das pastas
        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")

        if arquivo_csv:
            if not os.path.exists(os.path.dirname(arquivo_csv)):
                raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # Verificar o SRC da Camada
        crs = pontos_base.crs()

        if "UTM" in crs.description().upper():
            feedback.pushInfo(f"The layer 'Position Points of the Facade' is already in CRS UTM.")
        elif "WGS 84" in crs.description().upper() or "SIRGAS 2000" in crs.description().upper():
            crs = verificarCRS(pontos_base, feedback)
            nome = pontos_base.name() + "_reproject"
            pontos_base = QgsProject.instance().mapLayersByName(nome)[0]
        else:
            raise QgsProcessingException(f"❌ Layer must be WGS84 or SIRGAS2000 or UTM. Other ({crs.description().upper()}) not supported")

        # ===== Grava Parâmetros =====================================================
        saveParametros("VnoLF",
                        dist=parameters['dist'],
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        raster=raster_layer.source() if raster_layer else "",
                        csv=arquivo_csv,
                        altMin=parameters['alturaMin'],
                        dl=parameters['dl'],
                        df=parameters['df']) 

        # ===============================================================================
        # Reprojetar para WGS 84 (EPSG:4326)
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())
        # ===============================================================================

        # ===== Gerar as Geometrias =====================================================
        # 1. Obter pontos ordenados
        pontos = []

        for feat in pontos_base.getFeatures():
            geom = feat.geometry()
            if geom and not geom.isEmpty():
                pt = geom.asPoint()
                pontos.append(QgsPointXY(pt.x(), pt.y()))

        # 2. Criar linha base
        linha_base_geom = QgsGeometry.fromPolylineXY(pontos)

        if not linha_base_geom or linha_base_geom.isEmpty():
            raise QgsProcessingException("❌ Failed to create base line.")

        # 3. Suavizar
        linha_suavizada_geom = linha_base_geom.smooth(iterations=3, offset=0.25)

        if not linha_suavizada_geom or linha_suavizada_geom.isEmpty():
            raise QgsProcessingException("❌ Failed to smooth line.")

        # 4. Aplicar offset controlando lado
        linha_offset_geom = linha_suavizada_geom.offsetCurve(
            dist_fachada,
            segments=12,
            joinStyle=Qgis.JoinStyle.Round,
            miterLimit=2
        )

        if not linha_offset_geom or linha_offset_geom.isEmpty():
            raise QgsProcessingException("❌ Offset operation failed.")

        # Garantir singlepart
        if linha_offset_geom.isMultipart():
            partes = linha_offset_geom.asMultiPolyline()
            if not partes:
                raise QgsProcessingException("❌ Multipart geometry invalid.")
            linha_offset_geom = QgsGeometry.fromPolylineXY(partes[0])

        # 5. Converter para LineStringZ
        pts_z = []

        for pt in linha_offset_geom.asPolyline():
            pts_z.append(QgsPoint(pt.x(), pt.y(), 0))  # Z inicial = 0

        linha_final_geom = QgsGeometry.fromPolyline(pts_z)

        # 6. Criar camada final "Flight Line"
        flight_layer = QgsVectorLayer(
            f"LineStringZ?crs={crs.authid()}",
            "Flight Line",
            "memory"
        )

        prov = flight_layer.dataProvider()

        campos = QgsFields()
        campos.append(QgsField("id", QVariant.Int))
        campos.append(QgsField("height", QVariant.Double))
        prov.addAttributes(campos)
        flight_layer.updateFields()

        # 9. Aplicar simbologia
        symbol = QgsLineSymbol.createSimple({})
        symbol.setColor(QColor(255, 0, 0))  # vermelho
        symbol.setWidth(1)

        flight_layer.renderer().setSymbol(symbol)
        flight_layer.triggerRepaint()

        # 10. Mostra valores parciais
        geom = linha_final_geom  # já temos a geometria final
        dist = geom.length()
        feedback.pushInfo(f"✅ Flight Line Length: {round(dist, 2)} m")
 
        feedback.pushInfo(f"✅ Flight Line to Facade Distance: {round(dist_fachada, 2)}     Facade Height: {round(H, 2)}")

        # Sobreposições digitadas manualmente
        feedback.pushInfo(f"✅ Lateral Spacing: {round(deltaLat,2)}, Frontal Spacing: {round(deltaFront,2)}")

        # 11. Obtem as alturas das linhas de Voo (range só para números inteiros)
        alturas = [i for i in np.arange(h, H + h + 1, deltaLat)]

        if inverte:
            alturas = list(reversed(alturas))

        flight_layer.startEditing()

        id_counter = 1

        # Geometria base (2D)
        base_pts = linha_offset_geom.asPolyline()

        for altura in alturas:

            pts_z = []

            for pt in base_pts:
                pts_z.append(QgsPoint(pt.x(), pt.y(), float(altura)))

            geom_z = QgsGeometry.fromPolyline(pts_z)

            feat = QgsFeature(flight_layer.fields())
            feat.setGeometry(geom_z)
            feat["id"] = id_counter
            feat["height"] = float(altura)

            flight_layer.addFeature(feat)

            id_counter += 1

        flight_layer.commitChanges()
        flight_layer.updateExtents()

        # 12. Reprojetar linha Voo para WGS84 (4326)
        linha_voo_reproj = reprojeta_camada_WGS84(flight_layer, crs_wgs, transformador)

        # ===== LINHA VOO =================================
        QgsProject.instance().addMapLayer(linha_voo_reproj)


        # ===== Criar a camada Pontos de Fotos ==================================================================================
        pontos_fotos = QgsVectorLayer('Point?crs=' + crs.authid(), 'Photo Points', 'memory')
        pontos_provider = pontos_fotos.dataProvider()

        campos = QgsFields()
        campos.append(QgsField("id", QVariant.Int))
        campos.append(QgsField("linha", QVariant.Int))
        campos.append(QgsField("latitude", QVariant.Double))
        campos.append(QgsField("longitude", QVariant.Double))
        campos.append(QgsField("altitude", QVariant.Double))
        campos.append(QgsField("height", QVariant.Double))
        campos.append(QgsField("bowangle", QVariant.Double))
        pontos_provider.addAttributes(campos)
        pontos_fotos.updateFields()

        pontoID = 1
        tempo_total = 0

        # Transformador para MDE (se existir)
        param_kml = 'relativeToGround'
        if camadaMDE:
            param_kml = 'absolute'
            transformadorMDE = QgsCoordinateTransform(
                crs,
                camadaMDE.crs(),
                QgsProject.instance()
            )

        # Ponto de referência da fachada (primeiro ponto)
        feat_ref = next(pontos_base.getFeatures())
        ponto_fachada_ref = feat_ref.geometry().asPoint()

        for feat_linha in flight_layer.getFeatures():
            geom_linha = feat_linha.geometry()
            linha_id = feat_linha["id"]
            altura_voo = feat_linha["height"]

            distancias = list(np.arange(0, dist, deltaFront)) # dist é o comprimento da linha de voo

            # Garantir que o último ponto seja exatamente o final da linha
            if not math.isclose(distancias[-1], dist):
                distancias.append(dist)

            # Alternar sentido (zig-zag)
            if linha_id % 2 == 0:
                distancias = list(reversed(distancias))

            for d in distancias:
                ponto_geom = geom_linha.interpolate(d)
                ponto = ponto_geom.asPoint()

                # ----- Altitude do terreno -----
                altitude_terreno = 0

                if camadaMDE:
                    ponto_mde = transformadorMDE.transform(QgsPointXY(ponto.x(), ponto.y()))
                    value, ok = camadaMDE.dataProvider().sample(ponto_mde, 1)
                    altitude_terreno = value if ok else 0

                altitude_final = altitude_terreno + float(altura_voo)

                # ----- Converter para WGS84 -----
                ponto_wgs = transformador.transform(QgsPointXY(ponto.x(), ponto.y()))

                # ----- Criar feature -----
                f = QgsFeature(pontos_fotos.fields())
                f.setGeometry(QgsGeometry.fromPoint(QgsPoint(
                    ponto.x(),
                    ponto.y(),
                    altitude_final
                )))

                f["id"] = pontoID
                f["linha"] = linha_id
                f["latitude"] = ponto_wgs.y()
                f["longitude"] = ponto_wgs.x()
                f["altitude"] = altitude_final
                f["height"] = float(altura_voo)

                # ================= Calcular Bow Angle apontando para fachada =================
                eps = 0.01

                d_prev = max(d - eps, 0)
                d_next = min(d + eps, dist)

                pt1 = geom_linha.interpolate(d_prev)
                pt2 = geom_linha.interpolate(d_next)

                if pt1.isNull() or pt2.isNull():
                    continue

                p1 = pt1.asPoint()
                p2 = pt2.asPoint()

                # Vetor tangente local
                dx = p2.x() - p1.x()
                dy = p2.y() - p1.y()

                # Normal à direita
                nx = dy
                ny = -dx

                norm = math.hypot(nx, ny)
                if norm == 0:
                    continue

                nx /= norm
                ny /= norm

                # Vetor do ponto atual até um ponto da fachada
                vx = ponto_fachada_ref.x() - ponto.x()
                vy = ponto_fachada_ref.y() - ponto.y()

                # Produto escalar
                produto = nx * vx + ny * vy

                # Se estiver apontando para fora da fachada, inverter
                if produto < 0:
                    nx *= -1
                    ny *= -1

                # Converter para ângulo (0° = Norte)
                bowangle = math.degrees(math.atan2(nx, ny)) % 360

                f["bowangle"] = bowangle

                pontos_provider.addFeature(f)

                pontoID += 1

            # ----- Tempo estimado por linha -----
            tempo_linha = dist / velocidade
            tempo_total += tempo_linha

        pontos_fotos.updateExtents()
        # Reprojetar camada Pontos Fotos de UTM para WGS84 (4326)
        pontos_reproj = reprojeta_camada_WGS84(pontos_fotos, crs_wgs, transformador)

        # Point para PointZ
        if param_kml == 'absolute':
            pontos_reproj = set_Z_value(pontos_reproj, z_field="height")
            pontos_reproj = pontos3D(pontos_reproj)
            simbologiaPontos3D(pontos_reproj, "VF")
        else:
            pontos_reproj = set_Z_value(pontos_reproj, z_field="height")
            simbologiaPontos(pontos_reproj)
            
            QgsProject.instance().addMapLayer(pontos_reproj)

        feedback.pushInfo(f"✅ Total Estimated Flight Time: {tempo_total:.1f} s")
        feedback.pushInfo("✅ Photo Spots generated.")
        feedback.pushInfo("✅ Flight Line and Photo Spots completed.")

        # =============L I T C H I==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'): # Verificar se o caminho CSV está preenchido
            gerar_CSV("VF", pontos_reproj, arquivo_csv, velocidade, tempo, deltaFront, angulo_normal, H, gimbalAng, terrain)

            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Remover Camadas Reproject ===================================================

        removeLayersReproj('_reproject')

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Facade Vertical Flight Plan successfully executed.")
        feedback.pushInfo("")
        
        return {}

    def name(self):
        return 'Flight_Plan_V_noLF'

    def displayName(self):
        return self.tr('2. Non-Linear Facade')

    def group(self):
        return 'Vertical Flight'

    def groupId(self):
        return 'vertical'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_V_noLF()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Fachada,Vertical,Front,View,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Vertical.png'))

    texto = """This tool is designed for creating vertical flight plans tailored for mapping building facades, ideal for architectural projects and building inspections.
It enables the planning of a precise vertical trajectory with appropriate overlap and stop times for the drone, following terrain elevations (optionally), ensuring high-quality photographs and detailed mapping.</span></p>
<p class="MsoNormal"><b>Configuration Details:</b></p>
<ul style="margin-top: 0cm;" type="disc">
  <li><b><span>Estimated Facade Height:</span></b><span> Specifies the highest point of the facade to be mapped.</span></li>
  <li><b><span>Flight Base Line:</span></b><span> The path along which the drone will fly in front of the facade.</span></li>
  <li><b><span>Position of the Facade:</span></b><span> A reference point on the facade used to calculate overlap distances.</span></li>
</ul>
<p><span>The outputs are <b>CSV</b> file compatible with the <b>Litchi app</b>. and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
<p><b>
"""

    figura = 'images/Facade.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6023">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo