# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner H - using data from the Drone's camera sensors
                                 A QGIS plugin
 Flight Planner H
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França (Professor Ilton contributed to the project)
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França (Professor Ilton contributed to the project)'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli and Leandro França (Professor Ilton contributed to the project)'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer,
    distancia,
    pontos_na_linha,
    linhas_voo_poligono,
    heading_para_proximo,
    pontos_conexao
)

class PlanoVoo_H_Sensor(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooS, abGroundS, dlS, dfS, velocS, tStayS, gimbalS, csvS = loadParametros("H_Sensor")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno', 'Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooS))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundS))
        self.addParameter(QgsProcessingParameterNumber('percL','Side Overlap (75% = 0.75)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.30,maxValue=0.95,defaultValue=dlS))
        self.addParameter(QgsProcessingParameterNumber('percF','Forward Overlap (85% = 0.85)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.50,maxValue=0.95,defaultValue=dfS))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocS))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayS))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalS))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvS))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        percL = self.parameterAsDouble(parameters, 'percL', context)
        percF = self.parameterAsDouble(parameters, 'percF', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Drone Sensor Parameters from QGIS Settings - vindos do Calculator =========================
        s = QgsSettings()

        def get_setting_float(key):
            val = s.value(key)
            try:
                return float(val)
            except (TypeError, ValueError):
                return None

        drone = s.value("qgis-drone-flight-planner/nameDrone") or ""
        dc    = get_setting_float("qgis-drone-flight-planner/sensorH")
        dl    = get_setting_float("qgis-drone-flight-planner/sensorV")
        f     = get_setting_float("qgis-drone-flight-planner/dFocal")

        if not drone or dc is None or dl is None or f is None:
            raise QgsProcessingException("❌ Drone sensor data not found. Please configure the drone in the Calculator first!")

        feedback.pushInfo("")
        feedback.pushInfo(f"✅ Drone {drone}: sensor_width={dc}mm  sensor_height={dl}mm  focal={f}mm")

        # ===== Verificações =====================================================

        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Sensor",
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['percL'],
                        df=parameters['percF'])

        # ===============================================================================
        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Converter sensor de mm para graus 
        centroide = poligono_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        dc_g = meters2degrees(dc / 1000, latitude_ref, crs) 
        dl_g = meters2degrees(dl / 1000, latitude_ref, crs) 
        f_g  = meters2degrees(f  / 1000, latitude_ref, crs)  
        alt_g = meters2degrees(altVoo, latitude_ref, crs)     
        
        # Cálculo dos Espaçamentos Lateral e Frontal entre as fotografias
        tg_L = dc_g / (2 * f_g)
        D_lat = dc_g * alt_g / f_g
        SD_lat = percL * D_lat
        h1_L = SD_lat / (2 * tg_L)
        deltaLat = SD_lat * (alt_g / h1_L - 1)

        # Espaçamento frontal entre fotos
        tg_F = dl_g / (2 * f_g)
        D_front = dl_g * alt_g / f_g
        SD_front = percF * D_front
        h1_F = SD_front / (2 * tg_F)
        deltaFront = SD_front * (alt_g / h1_F - 1)

        # deltaFront em metros para o CSV
        deltaFront_m = deltaFront / meters2degrees(1, latitude_ref, crs)

        feedback.pushInfo(f"✅ Lateral spacing: {deltaLat:.6f}°  Frontal spacing: {deltaFront:.6f}°  ({deltaFront_m:.2f} m)")

        # Extrair coordenadas da linha base e do polígono 
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])
        p2 = QgsPointXY(linha_pts[1])
        
        # Gerar linhas de voo e montar LISTA_PONTOS em serpentina
        linhas_voo = linhas_voo_poligono(linha_geom, poligono_geom, pol_pts, p1, deltaLat)

        LISTA_PONTOS = []
        direcao = 1
        for geom_linha in linhas_voo:
            pontos = pontos_na_linha(geom_linha, deltaFront, altVoo, azimute)
            pontos_linha = pontos[::direcao]
            # Pontos de ligação entre linhas (quando deltaLat > deltaFront)
            if LISTA_PONTOS and pontos_linha:
                LISTA_PONTOS.extend(pontos_conexao(LISTA_PONTOS[-1], pontos_linha[0], altVoo))
            LISTA_PONTOS.extend(pontos_linha)
            direcao *= -1

        # Garantir que o voo começa pelo lado de p1 
        # Se o primeiro ponto de LISTA_PONTOS está mais longe de p1 que o último, inverter tudo
        if LISTA_PONTOS:
            d_ini = (LISTA_PONTOS[0]['longitude']  - p1.x())**2 + (LISTA_PONTOS[0]['latitude']  - p1.y())**2
            d_fim = (LISTA_PONTOS[-1]['longitude'] - p1.x())**2 + (LISTA_PONTOS[-1]['latitude'] - p1.y())**2
            if d_fim < d_ini:
                LISTA_PONTOS.reverse()

        # ===== Heading: cada ponto aponta para o próximo waypoint =======================================
        heading_para_proximo(LISTA_PONTOS, azimute)

        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(linhas_voo)} flight line(s).")

        # ============= L I T C H I ==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'):
            gerar_CSV("S", LISTA_PONTOS, arquivo_csv, velocidade, tempo, deltaFront_m, 0, altVoo, gimbalAng, terrain)
            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Criar KML do caminho (path) ===============================================        
        base, _ = os.path.splitext(arquivo_csv)
        caminho_kml = base + ".kml"
        salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

        self.csv_path = arquivo_csv
        self.kml_path = caminho_kml
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal Sensor Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv,
                'kml': caminho_kml}

    def name(self):
        return 'Flight_Plan_H_Sensor'

    def displayName(self):
        return self.tr('1. Following terrain - Sensor')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Sensor()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))
    
    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        s = QgsSettings()
        drone = s.value("qgis-drone-flight-planner/nameDrone", "No drone defined in Calculator")
        dc = s.value("qgis-drone-flight-planner/sensorH", "–")
        dl = s.value("qgis-drone-flight-planner/sensorV", "–")
        f = s.value("qgis-drone-flight-planner/dFocal", "–")

        texto = f"""
        <h3>Selected Drone from Calculator: <b style="font-size: 150%;">{drone}</b></h3>
        <p><b>Sensor Width:</b> {dc} mm &nbsp;&nbsp; <b>Sensor Height:</b> {dl} mm &nbsp;&nbsp; <b>Focal Length:</b> {f} mm</p>
        <p>This tool enables drone flight planning for photogrammetry, following terrain elevations (optionally), and calculating lateral and frontal overlaps based on the <b>drone's sensor parameters</b>.</p>
        <p>It generates a <b>CSV</b> file compatible with the <b>Litchi app</b> and two layers: <b>Flight Line</b> and <b>Photo Points</b>.</p>
        <p>It can also be used with other flight applications, utilizing the generated layers for flight lines and waypoints.</p>
        """

        corpo = f'''
        <div align="center">
            <img src="{os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura)}">
        </div>
        <div align="right">
            <p><b>Learn more:</b></p>
            <ul>
                <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a></li>
                <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6010">Click here to access the class with all the details about this tool!</a></li>
            </ul>
            <p><b>Autores: Prof Cazaroli & Leandro França</b></p>
            <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/">
                <img title="GeoOne" src="data:image/png;base64,{GeoOne}">
            </a>
            <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
        </div>
        '''
        return self.tr(texto) + corpo
    

    def postProcessAlgorithm(self, context, feedback):        
        
        # ================= Carregar KML no QGIS =================
        layer_kml = None

        if hasattr(self, 'kml_path') and self.kml_path and os.path.exists(self.kml_path):
            layer_kml = QgsVectorLayer(self.kml_path, 'path - ' + os.path.splitext(os.path.basename(self.kml_path))[0], "ogr")

            if layer_kml.isValid():
                QgsProject.instance().addMapLayer(layer_kml)
                feedback.pushInfo("✅ KML layer added to QGIS.")
            else:
                feedback.reportError("⚠️ KML file was created, but could not be loaded directly in QGIS.")

        # ================= Carregar CSV no QGIS =================
        layer_pontos = None

        if hasattr(self, 'csv_path') and self.csv_path:
            layer_pontos = csv_como_layer(self.csv_path, layer_name=None)

            if layer_pontos is None or not layer_pontos.isValid():
                feedback.reportError("❌ Could not load CSV as point layer.")
            else:
                QgsProject.instance().addMapLayer(layer_pontos)
                feedback.pushInfo("✅ CSV point layer added to QGIS.")

            try:
                params = { 'LAYER' : layer_pontos, 'STYLE_POINT' : 1 }
                processing.run("lftools:magicstyles", params)
            except:
                feedback.reportError("💡Install or enable the LFTools plugin to view the drone's heading, showing the direction its camera is pointing.")

        # ================= Abrir KML no Google Earth =================
        if hasattr(self, 'abrir_kml') and self.abrir_kml:
            if hasattr(self, 'kml_path') and self.kml_path and os.path.exists(self.kml_path):
                ok = QDesktopServices.openUrl(QUrl.fromLocalFile(self.kml_path))
                if ok:
                    feedback.pushInfo("✅ KML opened with the default application.")
                else:
                    feedback.reportError("⚠️ Could not open the KML automatically.")
            else:
                feedback.reportError("⚠️ KML path not found.")

        return {}