# -*- coding: utf-8 -*-

"""
/********************************************************************************
 Flight Planner H - Dji_Fly - Manually placed Side and Front distance data
                                 A QGIS plugin
 Flight Planner H - Dji_Fly
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-16
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
********************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França'
__date__ = '2025-05-16'
__copyright__ = '(C) 2025 by Prof Cazaroli and Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from ..images.Imgs import *
import os

from .Funcs import (
    meters2degrees,
    azimute,
    loadParametros,
    saveParametros,
    linhas_voo_poligono,
    heading_para_proximo,
    salvar_outputs,
    criar_layer_path,
    post_process_comum
)

class PlanoVoo_H_Dji_Fly(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooDji_Fly, abGroundDji_Fly, dlDji_Fly, gimbalDji_Fly, csvDji_Fly = loadParametros("H_Manual_Dji_Fly")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno','Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooDji_Fly))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundDji_Fly))
        self.addParameter(QgsProcessingParameterNumber('dl','Lateral Spacing Between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dlDji_Fly))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalDji_Fly))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvDji_Fly))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        deltaLat = self.parameterAsDouble(parameters, 'dl', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações =====================================================

        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Manual_Dji_Fly",
                        h=parameters['altura'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['dl'])

        # ===============================================================================
        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Transformar distancias para graus
        centroide = linha_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        # deltaLat: perpendicular às linhas → az_perp
        deltaLat_g = meters2degrees(deltaLat, latitude_ref, crs)

        feedback.pushInfo(f"✅ Lateral Spacing: {deltaLat:.2f} m")

        # Extrair coordenadas da linha base e do polígono 
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])

        # Gerar linhas de voo
        linhas_voo = linhas_voo_poligono(linha_geom, poligono_geom, pol_pts, p1, deltaLat_g)

        # Montar LISTA_PONTOS com waypoints de borda (10% do comprimento)
        # Cada linha: início → 10% → 90% → fim + ponto de conexão
        LISTA_PONTOS = []
        direcao = 1

        for geom_linha in linhas_voo:
            pts = geom_linha.asMultiPolyline()[0] if geom_linha.isMultipart() else geom_linha.asPolyline()
            if not pts:
                direcao *= -1
                continue

            p_ini = pts[0]
            p_fim = pts[-1]

            # Calcular ponto a 10% e 90% do comprimento
            dx = p_fim.x() - p_ini.x()
            dy = p_fim.y() - p_ini.y()

            p_10 = QgsPointXY(p_ini.x() + dx * 0.10, p_ini.y() + dy * 0.10)
            p_90 = QgsPointXY(p_ini.x() + dx * 0.90, p_ini.y() + dy * 0.90)

            if direcao == 1:
                pontos_linha = [
                    {'longitude': float(p_ini.x()), 'latitude': float(p_ini.y()), 'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_10.x()),  'latitude': float(p_10.y()),  'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_90.x()),  'latitude': float(p_90.y()),  'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_fim.x()), 'latitude': float(p_fim.y()), 'height': altVoo, 'bowangle': 0, 'foto': True},
                ]
            else:
                pontos_linha = [
                    {'longitude': float(p_fim.x()), 'latitude': float(p_fim.y()), 'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_90.x()),  'latitude': float(p_90.y()),  'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_10.x()),  'latitude': float(p_10.y()),  'height': altVoo, 'bowangle': 0, 'foto': True},
                    {'longitude': float(p_ini.x()), 'latitude': float(p_ini.y()), 'height': altVoo, 'bowangle': 0, 'foto': True},
                ]

            # Ponto de conexão entre linhas
            if LISTA_PONTOS and pontos_linha:
                from .Funcs import pontos_conexao
                LISTA_PONTOS.extend(pontos_conexao(LISTA_PONTOS[-1], pontos_linha[0], altVoo))

            LISTA_PONTOS.extend(pontos_linha)
            direcao *= -1

        # Heading
        heading_para_proximo(LISTA_PONTOS, azimute)
        self.layer_path = criar_layer_path(LISTA_PONTOS, arquivo_csv)

        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(linhas_voo)} flight line(s).")

        # ============= L I T C H I   &   K M L ==========================================================
        if arquivo_csv and arquivo_csv.endswith('.csv'):
            self.kml_path = salvar_outputs(LISTA_PONTOS, arquivo_csv, "H_Dji_Fly", 1, 0,
                                           0, 360, altVoo, gimbalAng, terrain)
            
            feedback.pushInfo("✅ CSV and KML files successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        self.csv_path  = arquivo_csv
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal Dji_Fly Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv, 'kml': self.kml_path}

    def name(self):
        return 'Flight_Plan_H_Dji_Fly'

    def displayName(self):
        return self.tr('3. Following terrain - Dji_Fly')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Dji_Fly()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))

    texto = """This tool allows for horizontal flight planning for drone photogrammetry, following terrain elevation based on the specified flight altitude and the lateral spacing between flight lines.</b>
<p>It generates a <b>CSV</b> file compatible with the <b>Litchi app</b> and two layers: <b>Flight Line</b> and <b>Photos Points</b>.</p>
<p>The CSV file can then be used with <b>Litchi Utilities</b> to generate a <b>KMZ</b> file for use in the <b>DJI Fly</b> app — extremely useful for drones equipped with the <b>Dji_Fly</b>, such as the <b>Mini 4 e 5 Pro, Lito X1, Air 3, Air 3S</b>, and <b>Mavic 3</b>.</p>
"""

    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6030">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                           layer_path=getattr(self, 'layer_path', None),
                           csv_path=getattr(self, 'csv_path', None),
                           kml_path=getattr(self, 'kml_path', None),
                           abrir_kml=getattr(self, 'abrir_kml', False))
        return {}