# -*- coding: utf-8 -*-

"""
/********************************************************************************
 Flight Planner H - RC2 Controller - Manually placed Side and Front distance data
                                 A QGIS plugin
 Flight Planner H - RC2 Controller
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-16
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
********************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França'
__date__ = '2025-05-16'
__copyright__ = '(C) 2025 by Prof Cazaroli and Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl, QVariant
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer,
    distancia,
    pontos_na_linha,
    linhas_voo_poligono,
    heading_para_proximo,
    pontos_conexao,
    criar_layer_path,
    montar_LISTA_PONTOS,
    salvar_outputs,
    post_process_comum
)

class PlanoVoo_H_RC2(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooRC2, abGroundRC2, dlRC2, gimbalRC2, csvRC2 = loadParametros("H_Manual_RC2_Controller")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno','Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooRC2))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundRC2))
        self.addParameter(QgsProcessingParameterNumber('dl','Lateral Spacing Between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dlRC2))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalRC2))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvRC2))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        deltaLat = self.parameterAsDouble(parameters, 'dl', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações =====================================================

        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Manual_RC2_Controller",
                        h=parameters['altura'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['dl'])

        # ===============================================================================
        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Transformar distancias para graus
        centroide = linha_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        deltaLat_g = meters2degrees(deltaLat, latitude_ref, crs)

        feedback.pushInfo(f"✅ Lateral Spacing: {deltaLat:.2f} m")

        # Extrair coordenadas da linha base e do polígono 
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])

        # Gerar linhas de voo e montar LISTA_PONTOS em serpentina
        linhas_voo = linhas_voo_poligono(linha_geom, poligono_geom, pol_pts, p1, deltaLat_g)
        LISTA_PONTOS = montar_LISTA_PONTOS(linhas_voo, 0, altVoo, azimute, p1, modo='bordas')
        heading_para_proximo(LISTA_PONTOS, azimute)
        self.layer_path = criar_layer_path(LISTA_PONTOS, arquivo_csv)

        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(linhas_voo)} flight line(s).")

        # ============= L I T C H I   &   K M L ==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'):
            self.kml_path = salvar_outputs(LISTA_PONTOS, arquivo_csv, "H_RC2", 1, 0,
                                           0, 360, altVoo, gimbalAng, terrain, 0)
            feedback.pushInfo("✅ CSV and KML files successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        self.csv_path  = arquivo_csv
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal RC2 Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv, 'kml': self.kml_path}

    def name(self):
        return 'Flight_Plan_H_RC2'

    def displayName(self):
        return self.tr('3. Following terrain - RC2 Controller')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_RC2()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))

    texto = """This tool allows for horizontal flight planning for drone photogrammetry, following terrain elevation based on the specified flight altitude and the lateral spacing between flight lines.</b>
<p>It generates a <b>CSV</b> file compatible with the <b>Litchi app</b> and two layers: <b>Flight Line</b> and <b>Photos Points</b>.</p>
<p>The CSV file can then be used with <b>Litchi Utilities</b> to generate a <b>KMZ</b> file for use in the <b>DJI Fly</b> app — extremely useful for drones equipped with the <b>RC2 Controller</b>, such as the <b>Mini 4 e 5 Pro, Air 3, Air 3S</b>, and <b>Mavic 3</b>.</p>
"""

    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6030">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                           layer_path=getattr(self, 'layer_path', None),
                           csv_path=getattr(self, 'csv_path', None),
                           kml_path=getattr(self, 'kml_path', None),
                           abrir_kml=getattr(self, 'abrir_kml', False))
        return {}