# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Vertical Facade
                                 A QGIS plugin
 Flight Planner VnoLF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-10
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2024-12-10'
__copyright__ = '(C) 2024 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer
)

class PlanoVoo_VF(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        distVF, hObjVF, altMinVF, dlVF, dfVF, velocVF, tStayVF, gimbalVF, rasterVF, csvVF = loadParametros("VF")

        self.addParameter(QgsProcessingParameterFeatureSource('linhaRef','Position of the Line on the Facade', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('dist','Distance from the Facade Flight Line (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=3,defaultValue=distVF))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=False))
        self.addParameter(QgsProcessingParameterBoolean('inverte','Reverse Flight Start',defaultValue=False))
        self.addParameter(QgsProcessingParameterNumber('altura','Facade Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hObjVF))
        self.addParameter(QgsProcessingParameterNumber('alturaMin','Start Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=altMinVF))
        self.addParameter(QgsProcessingParameterNumber('dl','Spacing between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.5,defaultValue=dlVF))
        self.addParameter(QgsProcessingParameterNumber('df','Spacing between Photos (m)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.5,defaultValue=dfVF))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocVF))
        self.addParameter(QgsProcessingParameterNumber('tempo','Wait time for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayVF))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalVF))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvVF))

    def processAlgorithm(self, parameters, context, feedback):
        
        # ===== Parâmetros de entrada para variáveis ====================================================
        linhaRef = self.parameterAsSource(parameters, 'linhaRef', context)
        dist_fachada = self.parameterAsDouble(parameters, 'dist', context)
        H = self.parameterAsDouble(parameters, 'altura', context)
        h = self.parameterAsDouble(parameters, 'alturaMin', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        inverte = self.parameterAsBool(parameters, 'inverte', context)
        deltaLat = self.parameterAsDouble(parameters, 'dl', context)
        deltaFront = self.parameterAsDouble(parameters, 'df', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações =============================================================================

        # A camada de entrada deve conter apenas 1 linha
        if linhaRef.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")
        
        # A geometria da linha deve ser válida
        feat = next(linhaRef.getFeatures())
        geom_ref = feat.geometry()
        if not geom_ref or geom_ref.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")
        
        # Número de vértices da linha linha deve ser igual o maior que 2
        num_vertices = sum(1 for _ in geom_ref.vertices())
        if num_vertices < 2:
            raise QgsProcessingException("❌ The line must contain at least 2 vertices!")
         
        # Verificar caminho das pastas
        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv:
            if not os.path.exists(os.path.dirname(arquivo_csv)):
                raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("VF",
                        dist=parameters['dist'],
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        raster="", # não usar esse parâmetro!!!!
                        csv=arquivo_csv,
                        altMin=parameters['alturaMin'],
                        dl=parameters['dl'],
                        df=parameters['df'])

        # ===============================================================================
        # Calcular offset da linha
        # Lendo a Linha de Referência da Fachada
        feat = next(linhaRef.getFeatures())
        linha_base_geom = feat.geometry()
        crs = linhaRef.sourceCrs()

        # Reprojetar para WGS 84
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())
        linha_base_geom.transform(transformador)

        # Transformar distancias para graus
        centroide = linha_base_geom.centroid().asPoint()
        latitude_ref = centroide.y()
        dist_fachada = meters2degrees(dist_fachada, latitude_ref, crs)
        deltaFront = meters2degrees(deltaFront, latitude_ref, crs)

        offset_geom = linha_base_geom.offsetCurve(
                                                    dist_fachada,  # distância
                                                    segments = 6,    # suavização de curvas
                                                    joinStyle = Qgis.JoinStyle.Round,   # Qgis.JoinStyle.Round, Qgis.JoinStyle.Miter, Qgis.JoinStyle.Bevel
                                                    miterLimit = 2.0
                                                    )
        

        # ===== Gerar as Geometrias =====================================================
        
        # obter pontos dentro da distância de cada linha
        def distancia(P1, P2):
            return np.sqrt((P1.x() - P2.x())**2 + (P1.y() - P2.y())**2)

        comprimento = offset_geom.length()
        if offset_geom.isMultipart():
            coord = offset_geom.asMultiPolyline()[0]
        else:
            coord = offset_geom.asPolyline()
        LISTA = []
        # Criar lista de pontos e distancias
        ListaDist = [0]
        soma = 0
        distSec = deltaFront # distância entre fotos (seções)

        for i in range(len(coord)-1):
            point1 = coord[i]
            point2 = coord[i+1]
            m = distancia(point1, point2)
            soma += m
            ListaDist += [soma]
        # Numero de Secoes e Nova Distancia
        if distSec < comprimento:
            NumSec = np.floor(comprimento/distSec)
            DistSecNova = comprimento/NumSec
            dist = np.arange(0, comprimento+DistSecNova, DistSecNova)
        else:
            NumSec, DistSecNova = 1, comprimento
            dist = np.arange(0, comprimento+DistSecNova, DistSecNova)
        # Cálculo do azimute - direção perpendicular à linha
        cont = 0
        for k in range(len(coord)-1):
            while ListaDist[k] <= dist[cont] and dist[cont] < ListaDist[k+1]:
                point1 = np.array([coord[k].x(), coord[k].y()])
                point2 = np.array([coord[k+1].x(), coord[k+1].y()])
                vetor = point2 - point1
                vetor/= np.linalg.norm(vetor)
                MultDist = dist[cont]-ListaDist[k]
                centro = point1 + vetor*MultDist
                # Pontos extremos de cada secao
                p1 = centro +  np.array([vetor[1], -1*vetor[0]])/2.0
                p2 = centro +  np.array([-1*vetor[1], vetor[0]])/2.0
                Az = azimute(QgsPointXY(float(p1[0]), float(p1[1])), QgsPointXY(float(p2[0]), float(p2[1])))[1]*180/np.pi
                LISTA += [  {'longitude':float(centro[0]), 
                            'latitude':float(centro[1]), 
                            'height':0, 
                            'bowangle': int(Az) }  ]
                cont +=1
                if cont == NumSec +1:
                    break
            if cont == NumSec +1:
                break
        # Última seção
        cont +=1
        point1 =  np.array([coord[-2].x(), coord[-2].y()])
        point2 =  np.array([coord[-1].x(), coord[-1].y()])
        vetor = point2 - point1
        vetor/= np.linalg.norm(vetor)
        centro =  np.array([coord[-1].x(), coord[-1].y()])
        p1 = centro +  np.array([vetor[1], -1*vetor[0]])/2.0
        p2 = centro +  np.array([-1*vetor[1], vetor[0]])/2.0
        Az = azimute(QgsPointXY(float(p1[0]), float(p1[1])), QgsPointXY(float(p2[0]), float(p2[1])))[1]*180/np.pi
        LISTA += [{'longitude':float(centro[0]), 
                    'latitude':float(centro[1]), 
                    'height':0, 
                    'bowangle': int(Az) }]
        
        # Fazer as linhas de voo paralelas
        alturas = np.arange(h, H + deltaLat, deltaLat) # de baixo para cima
        if inverte:
            alturas = alturas[::-1] # de cima para baixo
        LISTA_PONTOS = []
        direcao = 1
        for alt in alturas:
            for pnt in LISTA[::direcao]:
                novo_pnt = pnt.copy()
                novo_pnt['height'] = float(alt)
                LISTA_PONTOS.append(novo_pnt)
            direcao *= -1

        # ============= L I T C H I ==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'): # Verificar se o caminho CSV está preenchido
            gerar_CSV("VF", LISTA_PONTOS, arquivo_csv, velocidade, tempo, deltaFront, 0, H, gimbalAng, terrain)

            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Criar KML do caminho (path) ===============================================        
        base, ext = os.path.splitext(arquivo_csv)
        caminho_kml = base + ".kml"
        salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

        self.csv_path = arquivo_csv
        self.kml_path = caminho_kml
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Facade Vertical Flight Plan successfully executed.")
        feedback.pushInfo("")
        
        return {'csv': arquivo_csv,
                'kml': caminho_kml}

    def name(self):
        return 'Flight_Plan_VF'

    def displayName(self):
        return self.tr('1. Facade')

    def group(self):
        return 'Vertical Flight'

    def groupId(self):
        return 'vertical'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_VF()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Fachada,Facade,Vertical,Front,View,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Vertical.png'))

    texto = """This tool is designed for creating vertical flight plans tailored for mapping building facades, ideal for architectural projects and building inspections.
It enables the planning of a precise vertical trajectory with appropriate overlap and stop times for the drone, following terrain elevations (optionally), ensuring high-quality photographs and detailed mapping.</span></p>
<p class="MsoNormal"><b>Configuration Details:</b></p>
<ul style="margin-top: 0cm;" type="disc">
  <li><b><span>Estimated Facade Height:</span></b><span> Specifies the highest point of the facade to be mapped.</span></li>
  <li><b><span>Flight Base Line:</span></b><span> The path along which the drone will fly in front of the facade.</span></li>
</ul>
<p><span>The outputs are <b>CSV</b> file compatible with the <b>Litchi app</b>. and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
<p><b>
"""

    figura = 'images/Facade.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6023">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        
        # ================= Carregar KML no QGIS =================
        layer_kml = None

        if hasattr(self, 'kml_path') and self.kml_path and os.path.exists(self.kml_path):
            layer_kml = QgsVectorLayer(self.kml_path, 'path - ' + os.path.splitext(os.path.basename(self.kml_path))[0], "ogr")

            if layer_kml.isValid():
                QgsProject.instance().addMapLayer(layer_kml)
                feedback.pushInfo("✅ KML layer added to QGIS.")
            else:
                feedback.reportError("⚠️ KML file was created, but could not be loaded directly in QGIS.")

        
        # ================= Carregar CSV no QGIS =================
        layer_pontos = None

        if hasattr(self, 'csv_path') and self.csv_path:
            layer_pontos = csv_como_layer(self.csv_path, layer_name=None)

            if layer_pontos is None or not layer_pontos.isValid():
                feedback.reportError("❌ Could not load CSV as point layer.")
            else:
                QgsProject.instance().addMapLayer(layer_pontos)
                feedback.pushInfo("✅ CSV point layer added to QGIS.")

            try:
                params = { 'LAYER' : layer_pontos, 'STYLE_POINT' : 1 }
                processing.run("lftools:magicstyles", params)
            except:
                feedback.reportError("💡Install or enable the LFTools plugin to view the drone's heading, showing the direction its camera is pointing.")


        # ================= Abrir KML no Google Earth =================
        if hasattr(self, 'abrir_kml') and self.abrir_kml:
            if hasattr(self, 'kml_path') and self.kml_path and os.path.exists(self.kml_path):
                ok = QDesktopServices.openUrl(QUrl.fromLocalFile(self.kml_path))
                if ok:
                    feedback.pushInfo("✅ KML opened with the default application.")
                else:
                    feedback.reportError("⚠️ Could not open the KML automatically.")
            else:
                feedback.reportError("⚠️ KML path not found.")

        return {}