# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner H - using data from the Drone's camera sensors
                                 A QGIS plugin
 Flight Planner H
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França (Professor Ilton contributed to the project)
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França (Professor Ilton contributed to the project)'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli and Leandro França (Professor Ilton contributed to the project)'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from ..images.Imgs import *
import os

from .Funcs import (
    meters2degrees,
    azimute,
    loadParametros,
    saveParametros,
    linhas_voo_poligono,
    heading_para_proximo,
    criar_layer_path,
    montar_LISTA_PONTOS,
    salvar_outputs,
    post_process_comum
)


class PlanoVoo_H_Sensor(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooS, abGroundS, dlS, dfS, velocS, tStayS, gimbalS, csvS = loadParametros("H_Sensor")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno', 'Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooS))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundS))
        self.addParameter(QgsProcessingParameterNumber('percL','Side Overlap (75% = 0.75)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.30,maxValue=0.95,defaultValue=dlS))
        self.addParameter(QgsProcessingParameterNumber('percF','Forward Overlap (85% = 0.85)',
                                                       type=QgsProcessingParameterNumber.Double,
                                                       minValue=0.50,maxValue=0.95,defaultValue=dfS))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocS))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayS))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalS))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvS))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        percL = self.parameterAsDouble(parameters, 'percL', context)
        percF = self.parameterAsDouble(parameters, 'percF', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Drone Sensor Parameters from QGIS Settings - vindos do Calculator =========================
        s = QgsSettings()

        def get_setting_float(key):
            val = s.value(key)
            try:
                return float(val)
            except (TypeError, ValueError):
                return None

        drone = s.value("qgis-drone-flight-planner/nameDrone") or ""
        dc    = get_setting_float("qgis-drone-flight-planner/sensorH")
        dl    = get_setting_float("qgis-drone-flight-planner/sensorV")
        f     = get_setting_float("qgis-drone-flight-planner/dFocal")

        if not drone or dc is None or dl is None or f is None:
            raise QgsProcessingException("❌ Drone sensor data not found. Please configure the drone in the Calculator first!")

        feedback.pushInfo("")
        feedback.pushInfo(f"✅ Drone {drone}: sensor_width={dc}mm  sensor_height={dl}mm  focal={f}mm")

        # ===== Verificações =====================================================

        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Sensor",
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['percL'],
                        df=parameters['percF'])

        # ===============================================================================
        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Converter sensor de mm para graus 
        centroide = poligono_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        dc_g = meters2degrees(dc / 1000, latitude_ref, crs) 
        dl_g = meters2degrees(dl / 1000, latitude_ref, crs) 
        f_g  = meters2degrees(f  / 1000, latitude_ref, crs)  
        alt_g = meters2degrees(altVoo, latitude_ref, crs)

        # Cálculo dos Espaçamentos Lateral e Frontal entre as fotografias
        tg_L = dc_g / (2 * f_g)
        D_lat = dc_g * alt_g / f_g
        SD_lat = percL * D_lat
        h1_L = SD_lat / (2 * tg_L)
        deltaLat = SD_lat * (alt_g / h1_L - 1)

        # Espaçamento frontal entre fotos
        tg_F = dl_g / (2 * f_g)
        D_front = dl_g * alt_g / f_g
        SD_front = percF * D_front
        h1_F = SD_front / (2 * tg_F)
        deltaFront = SD_front * (alt_g / h1_F - 1)

        # deltaFront em metros para o CSV
        deltaLat_m = deltaLat / meters2degrees(1, latitude_ref, crs)
        deltaFront_m = deltaFront / meters2degrees(1, latitude_ref, crs)

        feedback.pushInfo(f"✅ Lateral spacing: {deltaLat_m:.2f} m  Frontal spacing: {deltaFront_m:.2f} m")

        # Extrair coordenadas da linha base e do polígono
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])

        # ===== Linhas de voo ============================================================================
        linhas_voo = linhas_voo_poligono(linha_geom, poligono_geom, pol_pts, p1, deltaLat)

        # ===== LISTA_PONTOS =============================================================================
        LISTA_PONTOS = montar_LISTA_PONTOS(linhas_voo, deltaFront, altVoo, azimute, p1, modo='distancia')
        
        heading_para_proximo(LISTA_PONTOS, azimute)
        self.layer_path = criar_layer_path(LISTA_PONTOS, arquivo_csv)

        feedback.pushInfo(f"\u2705 {len(LISTA_PONTOS)} waypoints generated across {len(linhas_voo)} flight line(s).")

        # ============= L I T C H I   &   K M L ==========================================================
        if arquivo_csv and arquivo_csv.endswith('.csv'):
            self.kml_path = salvar_outputs(LISTA_PONTOS, arquivo_csv, "S", velocidade, tempo,
                                               deltaFront, 0, altVoo, gimbalAng, terrain, None)
            
            feedback.pushInfo("✅ CSV and KML files successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        self.csv_path  = arquivo_csv
        self.abrir_kml = abrir_kml

        # ============= Encerramento ==========================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal Manual Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv, 'kml': self.kml_path}

    def name(self):
        return 'Flight_Plan_H_Sensor'

    def displayName(self):
        return self.tr('1. Following terrain - Sensor')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Sensor()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))
    
    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        s = QgsSettings()
        drone = s.value("qgis-drone-flight-planner/nameDrone", "No drone defined in Calculator")
        dc = s.value("qgis-drone-flight-planner/sensorH", "–")
        dl = s.value("qgis-drone-flight-planner/sensorV", "–")
        f = s.value("qgis-drone-flight-planner/dFocal", "–")

        texto = f"""
        <h3>Selected Drone from Calculator: <b style="font-size: 150%;">{drone}</b></h3>
        <p><b>Sensor Width:</b> {dc} mm &nbsp;&nbsp; <b>Sensor Height:</b> {dl} mm &nbsp;&nbsp; <b>Focal Length:</b> {f} mm</p>
        <p>This tool enables drone flight planning for photogrammetry, following terrain elevations (optionally), and calculating lateral and frontal overlaps based on the <b>drone's sensor parameters</b>.</p>
        <p>It generates a <b>CSV</b> file compatible with the <b>Litchi app</b> and two layers: <b>Flight Line</b> and <b>Photo Points</b>.</p>
        <p>It can also be used with other flight applications, utilizing the generated layers for flight lines and waypoints.</p>
        """

        corpo = f'''
        <div align="center">
            <img src="{os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura)}">
        </div>
        <div align="right">
            <p><b>Learn more:</b></p>
            <ul>
                <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a></li>
                <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6010">Click here to access the class with all the details about this tool!</a></li>
            </ul>
            <p><b>Autores: Prof Cazaroli & Leandro França</b></p>
            <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/">
                <img title="GeoOne" src="data:image/png;base64,{GeoOne}">
            </a>
            <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
        </div>
        '''
        return self.tr(texto) + corpo
    

    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                           layer_path=getattr(self, 'layer_path', None),
                           csv_path=getattr(self, 'csv_path', None),
                           kml_path=getattr(self, 'kml_path', None),
                           abrir_kml=getattr(self, 'abrir_kml', False))
        return {}