# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Vertical Flight Circular
                                 A QGIS plugin
 Flight Planner VC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-09
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    loadParametros,
    saveParametros,
    salvar_outputs,
    criar_layer_path,
    post_process_comum
)

class PlanoVoo_VC(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        pontoInicialVC, hObjVC, altMinVC, anguloFotoVC, dVertVC, velocVC, tStayVC, gimbalVC, csvVC = loadParametros("VC")

        self.addParameter(QgsProcessingParameterFeatureSource('circuloRef','Flight Base Circle', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterNumber('ponto_inicial','Start Point (0 a 359 degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=359,defaultValue=pontoInicialVC))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=False))
        self.addParameter(QgsProcessingParameterBoolean('inverte','Reverse Flight Start',defaultValue=False))
        self.addParameter(QgsProcessingParameterNumber('altura','Object Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hObjVC))
        self.addParameter(QgsProcessingParameterNumber('alturaMin','Start Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=altMinVC))
        self.addParameter(QgsProcessingParameterNumber('deltaVertical','Vertical Spacing (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dVertVC))
        self.addParameter(QgsProcessingParameterNumber('anguloFoto', 'Angle in degrees between Photos (360.0 / numPartes) (1 a 90 degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=1, maxValue=90, defaultValue=anguloFotoVC))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocVC))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayVC))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalVC))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvVC))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ===========================================
        circuloRef   = self.parameterAsSource(parameters, 'circuloRef', context)
        ponto_inicial = self.parameterAsInt(parameters, 'ponto_inicial', context)
        H            = self.parameterAsDouble(parameters, 'altura', context)
        h            = self.parameterAsDouble(parameters, 'alturaMin', context)
        terrain      = self.parameterAsBool(parameters, 'aboveGround', context)
        inverte      = self.parameterAsBool(parameters, 'inverte', context)
        anguloFoto   = self.parameterAsDouble(parameters, 'anguloFoto', context)  # graus entre fotos
        deltaV       = self.parameterAsDouble(parameters, 'deltaVertical', context)
        velocidade   = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo        = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng    = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv  = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml    = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações ==================================================================

        if circuloRef.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 circle feature!")

        feat = next(circuloRef.getFeatures())
        geom_ref = feat.geometry()
        if not geom_ref or geom_ref.isEmpty():
            raise QgsProcessingException("❌ Invalid circle geometry!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("VC",
                        pontoInicial=parameters['ponto_inicial'],
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        altMin=parameters['alturaMin'],
                        anguloFotoVC=parameters['anguloFoto'],
                        dVertVC=parameters['deltaVertical'])

        # ===============================================================================
        # Lendo a Linha de Referência da Fachada
        feat = next(circuloRef.getFeatures())
        circulo_base_geom = feat.geometry()
        crs = circuloRef.sourceCrs()
        
        # Reprojetar para WGS 84
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())
        circulo_base_geom.transform(transformador)

        # Obter Centro e Raio para o Cálculo Circular
        centroide = circulo_base_geom.centroid().asPoint()
        cx, cy = centroide.x(), centroide.y()
        
        # Cálculo do Raio: Distância do centro ao primeiro vértice da borda do círculo
        if circulo_base_geom.isMultipart():
            ponto_borda = circulo_base_geom.asMultiPolygon()[0][0][0]
        else:
            ponto_borda = circulo_base_geom.asPolygon()[0][0]

        raio = math.sqrt((ponto_borda.x() - cx)**2 + (ponto_borda.y() - cy)**2)

        # Número de pontos por volta calculado pelo ângulo entre fotos
        numPartes = max(4, int(round(360.0 / anguloFoto)))
        passo_angular = 360.0 / numPartes

        # Comprimento do arco entre fotos (para o CSV)
        deltaFront_m = 2 * math.pi * raio * anguloFoto / 360.0

        feedback.pushInfo(f"✅ Radius: {raio:.4f}°  Angle between photos: {anguloFoto:.1f}°  "
                          f"→ {numPartes} points/circle  Arc spacing: {deltaFront_m:.2f}°")

        # Gerar LISTA_BASE de pontos sobre o círculo
        LISTA_BASE = []
        for i in range(numPartes):
            angulo_graus = i * passo_angular
            angulo_rad   = math.radians(angulo_graus)

            px = cx + raio * math.sin(angulo_rad)
            py = cy + raio * math.cos(angulo_rad)

            # Bowangle: drone aponta para o centro
            dx = cx - px
            dy = cy - py
            azimute_centro = math.degrees(math.atan2(dx, dy)) % 360

            LISTA_BASE.append({
                'longitude':         float(px),
                'latitude':          float(py),
                'height':            0.0,
                'bowangle':          int(azimute_centro),
                'angulo_referencia': angulo_graus
            })

        # Ajustar ponto inicial pelo azimute digitado
        idx_inicio = min(range(len(LISTA_BASE)),
                         key=lambda i: abs(LISTA_BASE[i]['angulo_referencia'] - (ponto_inicial % 360)))
        LISTA_BASE = LISTA_BASE[idx_inicio:] + LISTA_BASE[:idx_inicio]

        # Gerar LISTA_PONTOS (serpentina por alturas)
        alturas = np.arange(h, H + deltaV, deltaV) # de baixo para cima
        if inverte:
            alturas = alturas[::-1] # de cima para baixo

        LISTA_PONTOS = []
        direcao = 1
        for i, alt in enumerate(alturas):
            for pnt in LISTA_BASE[::direcao]:
                novo_pnt = pnt.copy()
                novo_pnt['height'] = float(alt)
                del novo_pnt['angulo_referencia']
                LISTA_PONTOS.append(novo_pnt)
            # Marcar último ponto do nível como conexão
            if i < len(alturas) - 1:
                LISTA_PONTOS[-1]['foto'] = False
            direcao *= -1

        self.layer_path = criar_layer_path(LISTA_PONTOS, arquivo_csv)

        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(alturas)} flight level(s).")

        # ============= L I T C H I   &   K M L ==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'):
            self.kml_path = salvar_outputs(LISTA_PONTOS, arquivo_csv, "VC", velocidade, tempo,
                                           deltaFront_m, 0, H, gimbalAng, terrain)
            feedback.pushInfo("✅ CSV and KML files successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        self.csv_path  = arquivo_csv
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Circular Vertical Flight Plan successfully executed.")
        feedback.pushInfo("")
        
        return {'csv': arquivo_csv, 'kml': self.kml_path}

    def name(self):
        return 'Flight_Plan_VC'

    def displayName(self):
        return self.tr('2. Circular')

    def group(self):
        return 'Vertical Flight'

    def groupId(self):
        return 'vertical'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_VC()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,orbital,focal,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Vertical.png'))

    texto = """This tool is designed to plan vertical and circular flights, ideal for 3D inspection and mapping projects around towers and similar objects.<br>
It enables the creation of an optimized flight path to capture detailed images of the object's surroundings. Following terrain elevations (optionally).
<p><b>Required configurations:</b></p>
<ul>
  <li><b>Estimated object height:</b><span> Defines the highest point of the structure to be inspected.<o:p></o:p></span></li>
  <li class="MsoNormal" style=""><b><span>Vertical spacing:</span></b><span> Determines the distance between capture levels along the object's height.<o:p></o:p></span></li>
  <li class="MsoNormal" style=""><b><span>Number of photos per base circle (segments):</span></b><span> Specifies the number of photos to be captured at each circular level.<o:p></o:p></span></li>
</ul>
<p><span>The outputs are <b>CSV</b> file compatible with the <b>Litchi app</b>. and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
            """

    figura = 'images/Circular.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6024">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    

    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                           layer_path=getattr(self, 'layer_path', None),
                           csv_path=getattr(self, 'csv_path', None),
                           kml_path=getattr(self, 'kml_path', None),
                           abrir_kml=getattr(self, 'abrir_kml', False))
        return {}