# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner - Vertical Flight Circular
                                 A QGIS plugin
 Flight Planner VC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-12-09
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli e Leandro França'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli e Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer
)

class PlanoVoo_VC(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        pontoInicialVC, hObjVC, altMinVC, nPartesVC, dVertVC, velocVC, tStayVC, gimbalVC, csvVC = loadParametros("VC")

        self.addParameter(QgsProcessingParameterFeatureSource('circuloRef','Flight Base Circle', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterNumber('ponto_inicial','Start Point (0 a 359 degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=359,defaultValue=pontoInicialVC))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=False))
        self.addParameter(QgsProcessingParameterBoolean('inverte','Reverse Flight Start',defaultValue=False))
        self.addParameter(QgsProcessingParameterNumber('altura','Object Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hObjVC))
        self.addParameter(QgsProcessingParameterNumber('alturaMin','Start Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=altMinVC))
        self.addParameter(QgsProcessingParameterNumber('numpartes','Horizontal Division into PARTS of Base Circle',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=4,defaultValue=nPartesVC))
        self.addParameter(QgsProcessingParameterNumber('deltaVertical','Vertical Spacing (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dVertVC))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocVC))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayVC))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalVC))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvVC))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ===========================================
        circuloRef = self.parameterAsSource(parameters, 'circuloRef', context)
        ponto_inicial = self.parameterAsInteger(parameters, 'ponto_inicial', context)
        H = self.parameterAsDouble(parameters, 'altura', context)
        h = self.parameterAsDouble(parameters, 'alturaMin', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        inverte = self.parameterAsBool(parameters, 'inverte', context)
        numpartes = self.parameterAsInteger(parameters, 'numpartes', context) # deltaH será calculado
        deltaV = self.parameterAsDouble(parameters, 'deltaVertical', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações ==================================================================
        if circuloRef.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 circle feature!")
        
        # A geometria da linha deve ser válida
        feat = next(circuloRef.getFeatures())
        geom_ref = feat.geometry()
        if not geom_ref or geom_ref.isEmpty():
            raise QgsProcessingException("❌ Invalid circle geometry!")
        
        # Verificar caminho das pastas
        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv:
            if not os.path.exists(os.path.dirname(arquivo_csv)):
                raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("VC",
                        ponto_inicial=parameters['ponto_inicial'],
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        altMin=parameters['alturaMin'],
                        nPartesVC=parameters['numpartes'],
                        dVertVC=parameters['deltaVertical'])

        # ===============================================================================
        # Reprojetar para WGS 84
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())
        circulo_base_geom.transform(transformador)

        # Obter Centro e Raio para o Cálculo Circular
        centroide = circulo_base_geom.centroid().asPoint()
        cx, cy = centroide.x(), centroide.y()
        
        # Cálculo do Raio: Distância do centro ao primeiro vértice da borda do círculo
        if circulo_base_geom.isMultipart():
            ponto_borda = circulo_base_geom.asMultiPolyline()[0][0]
        else:
            ponto_borda = circulo_base_geom.asPolyline()[0]
        
        raio = math.sqrt((ponto_borda.x() - cx)**2 + (ponto_borda.y() - cy)**2)

        # Gerar a LISTA base de pontos sobre o círculo (divisão por numPartes)
        LISTA_BASE = []
        passo_angular = 360.0 / numPartes      

        for i in range(numPartes):
            # Ângulo atual em graus (iniciando do Norte/0°)
            angulo_graus = i * passo_angular
            angulo_rad = math.radians(angulo_graus)

            # Coordenadas sobre a linha circular (X=seno, Y=cosseno para Azimute Norte)
            px = cx + raio * math.sin(angulo_rad)
            py = cy + raio * math.cos(angulo_rad)

            # Cálculo do Bow Angle: O drone deve olhar para o centro do círculo
            # Vetor do ponto (px, py) para o centro (cx, cy)
            dx = cx - px
            dy = cy - py
            # math.atan2(dx, dy) retorna o azimute em radianos para o sistema náutico
            azimute_para_centro = math.degrees(math.atan2(dx, dy)) % 360

            LISTA_BASE.append({
                'longitude': float(px),
                'latitude': float(py),
                'height': 0.0,
                'bowangle': int(azimute_para_centro),
                'angulo_referencia': angulo_graus
            })

        # Ajustar Ponto Inicial baseado no Azimute fornecido (ponto_inicial_az)
        # Encontra o índice na lista que mais se aproxima do azimute inicial desejado
        idx_inicio = min(range(len(LISTA_BASE)), 
                        key=lambda i: abs(LISTA_BASE[i]['angulo_referencia'] - (ponto_inicial_az % 360)))
        
        # Rotaciona a lista para começar no ponto do azimute escolhido
        LISTA_BASE = LISTA_BASE[idx_inicio:] + LISTA_BASE[:idx_inicio]

        # Gerar as linhas de voo paralelas (Alturas) - Alturas de h até H com espaçamento dVertVC
        alturas = np.arange(h, H + dVertVC, dVertVC)
        
        if inverte:
            alturas = alturas[::-1] # De cima para baixo se REVERSE estiver ticado

        LISTA_PONTOS = []
        direcao = 1 # Controle para efeito snake (zigue-zague)

        for alt in alturas:
            # Itera sobre a LISTA_BASE seguindo a direção atual
            fatiada = LISTA_BASE[::direcao]
            for pnt in fatiada:
                novo_pnt = pnt.copy()
                novo_pnt['height'] = float(alt)
                # Remove o dado auxiliar de ordenação para limpar a saída
                del novo_pnt['angulo_referencia']
                LISTA_PONTOS.append(novo_pnt)
            
            # Inverte a direção para a próxima altura (snake pattern)
            direcao *= -1

        # ============= L I T C H I ================================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'):
            gerar_CSV("VC", LISTA_PONTOS, arquivo_csv, velocidade, tempo, deltaH, 0, H, gimbalAng, terrain)
            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Criar KML do caminho (path) ===============================================        
        base, ext = os.path.splitext(arquivo_csv)
        caminho_kml = base + ".kml"
        salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

        self.csv_path = arquivo_csv
        self.kml_path = caminho_kml
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Circular Vertical Flight Plan successfully executed.")
        feedback.pushInfo("")
        
        return {'csv': arquivo_csv,
                'kml': caminho_kml}

    def name(self):
        return 'Flight_Plan_VC'

    def displayName(self):
        return self.tr('2. Circular')

    def group(self):
        return 'Vertical Flight'

    def groupId(self):
        return 'vertical'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_VC()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,orbital,focal,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Vertical.png'))

    texto = """This tool is designed to plan vertical and circular flights, ideal for 3D inspection and mapping projects around towers and similar objects.<br>
It enables the creation of an optimized flight path to capture detailed images of the object's surroundings. Following terrain elevations (optionally).
<p><b>Required configurations:</b></p>
<ul>
  <li><b>Estimated object height:</b><span> Defines the highest point of the structure to be inspected.<o:p></o:p></span></li>
  <li class="MsoNormal" style=""><b><span>Vertical spacing:</span></b><span> Determines the distance between capture levels along the object's height.<o:p></o:p></span></li>
  <li class="MsoNormal" style=""><b><span>Number of photos per base circle (segments):</span></b><span> Specifies the number of photos to be captured at each circular level.<o:p></o:p></span></li>
</ul>
<p><span>The outputs are <b>CSV</b> file compatible with the <b>Litchi app</b>. and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
            """

    figura = 'images/Circular.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6024">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo