# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner H Linear - Manually placed Side and Front distance data
                                 A QGIS plugin
 Flight Planner H Linear
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-21
        copyright            : (C) 2025 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França'
__date__ = '2025-11-21'
__copyright__ = '(C) 2025 by Prof Cazaroli and Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer,
    distancia,
    pontos_na_linha,
    heading_para_proximo,
    pontos_conexao,
    criar_layer_path,
    montar_LISTA_PONTOS,
    salvar_outputs,
    post_process_comum
)

class PlanoVoo_H_Line(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooL, abGroundL, dlL, nLinL, dfL, velocL, tStayL, gimbalL, csvL = loadParametros("H_Line")

        self.addParameter(QgsProcessingParameterFeatureSource('linhaRef','Axis Line', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooL))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)',defaultValue=abGroundL))

        frontal_opts = [self.tr('2 Lines'), self.tr('3 Lines (Axis included)'), self.tr('4 Lines'), self.tr('5 Lines (Axis include)')]
        self.addParameter(QgsProcessingParameterEnum('nLinhas', self.tr('Number of Flight Routes (from 1 to 5)'), options = frontal_opts, defaultValue= nLinL))

        self.addParameter(QgsProcessingParameterNumber('bf','Lateral Buffer (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dlL))
        
        self.addParameter(QgsProcessingParameterNumber('df','Front Spacing Between Photos (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=1,defaultValue=dfL))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocL))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayL))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalL))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvL))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        linhaRef = self.parameterAsSource(parameters, 'linhaRef', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        n_linhas = parameters['nLinhas']
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        deltaLat = self.parameterAsDouble(parameters, 'bf', context)
        deltaFront = self.parameterAsDouble(parameters, 'df', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)
        
        # ===== Verificações =============================================================================

        if linhaRef.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat = next(linhaRef.getFeatures())
        geom_ref = feat.geometry()
        if not geom_ref or geom_ref.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in geom_ref.vertices())
        if num_vertices < 2:
            raise QgsProcessingException("❌ The line must contain at least 2 vertices!")

        # n_linhas: 0=2 linhas, 1=3 linhas (eixo), 2=4 linhas, 3=5 linhas (eixo)
        incluir_eixo = n_linhas in (1, 3)
        dois_buffers = n_linhas in (2, 3)

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv:
            if not os.path.exists(os.path.dirname(arquivo_csv)):
                raise QgsProcessingException("❌ Path to CSV file does not exist!")
    
        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Line",
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['bf'],
                        df=parameters['df'],
                        dfop=parameters['nLinhas']
                        )

        # ===============================================================================
        # Lendo a Linha de Referência do trajeto de voo
        feat = next(linhaRef.getFeatures())
        linha_base_geom = feat.geometry()
        crs = linhaRef.sourceCrs()

        # Reprojetar para WGS 84
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())
        linha_base_geom.transform(transformador)

        # Extrair coordenadas da linha base
        if linha_base_geom.isMultipart():
            coord_base = linha_base_geom.asMultiPolyline()[0]
        else:
            coord_base = linha_base_geom.asPolyline()

        # Transformar distâncias para graus
        centroide = linha_base_geom.centroid().asPoint()
        latitude_ref = centroide.y()
        deltaFront_graus = meters2degrees(deltaFront, latitude_ref, crs)
        deltaLat_graus   = meters2degrees(deltaLat,   latitude_ref, crs)

        # Calcular offsets laterais - distâncias de offset de cada linha em relação ao eixo
        # com eixo: ±1×dl, ±2×dl   sem eixo: ±0.5×dl, ±1.5×dl
        if incluir_eixo:
            offsets = [-2 * deltaLat_graus, -deltaLat_graus, 0, deltaLat_graus, 2 * deltaLat_graus]
        else:
            offsets = [-1.5 * deltaLat_graus, -0.5 * deltaLat_graus, 0.5 * deltaLat_graus, 1.5 * deltaLat_graus]

        # Filtrar eixo se não incluso e, se não dois buffers, remover externos
        if not incluir_eixo:
            offsets_filtrados = offsets  # já sem o 0
        else:
            offsets_filtrados = offsets

        if not dois_buffers:
            # Manter apenas os 3 centrais (ou 2 se sem eixo)
            if incluir_eixo:
                offsets_filtrados = [-deltaLat_graus, 0, deltaLat_graus]
            else:
                offsets_filtrados = [-0.5 * deltaLat_graus, 0.5 * deltaLat_graus]

        # Determinar lado inicial pela orientação da linha 
        inicio = coord_base[0]
        fim    = coord_base[-1]
        dx = fim.x() - inicio.x()
        dy = fim.y() - inicio.y()

        # Linha mais horizontal → começa pela direita (offset negativo); mais vertical → esquerda
        if abs(dx) >= abs(dy):
            offsets_ordenados = sorted(offsets_filtrados, reverse=True)   # direita → esquerda (neg→pos)
        else:
            offsets_ordenados = sorted(offsets_filtrados)                  # esquerda → direita

        # Montar LISTA_PONTOS em padrão serpentina
        LISTA_PONTOS = []
        direcao = 1  # 1 = frente, -1 = invertido (serpentina)

        for offset in offsets_ordenados:
            if offset == 0:
                geom_linha = linha_base_geom
            else:
                geom_linha = linha_base_geom.offsetCurve(
                    offset,
                    segments=8,
                    joinStyle=Qgis.JoinStyle.Round,
                    miterLimit=2.0
                )
                if not geom_linha or geom_linha.isEmpty():
                    geom_linha = linha_base_geom

            pontos = pontos_na_linha(geom_linha, deltaFront_graus, altVoo, azimute)
            pontos_linha = pontos[::direcao]
            # Pontos de ligação entre linhas (quando deltaLat > deltaFront)
            if LISTA_PONTOS and pontos_linha:
                LISTA_PONTOS.extend(pontos_conexao(LISTA_PONTOS[-1], pontos_linha[0], altVoo))
            LISTA_PONTOS.extend(pontos_linha)
            direcao *= -1
        
        # Heading: cada ponto aponta para o próximo waypoint
        heading_para_proximo(LISTA_PONTOS, azimute)

        # =============L I T C H I==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'): # Verificar se o caminho CSV está preenchido
            gerar_CSV("L", LISTA_PONTOS, arquivo_csv, velocidade, tempo, deltaFront, 0, altVoo, gimbalAng, terrain, n_linhas)

            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Criar KML do caminho (path) ===============================================        
        base, ext = os.path.splitext(arquivo_csv)
        caminho_kml = base + ".kml"
        salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

        self.csv_path = arquivo_csv
        self.kml_path = caminho_kml
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(offsets_ordenados)} flight line(s).")
        feedback.pushInfo("✅ Horizontal Linear Flight Plan successfully executed.")
        feedback.pushInfo("")
        
        return {'csv': arquivo_csv,
                'kml': caminho_kml}

    def name(self):
        return 'Flight_Plan_H_Line'

    def displayName(self):
        return self.tr('4. Following terrain - Line')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Line()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne,Linear,Track,Road,Line,Channel').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))

    texto = """This tool generates a <b>horizontal linear flight plan</b> from a single <b>axis line</b>, creating <b>2 to 5 parallel flight routes</b> with automatically placed photo waypoints.
<p>
You define the <b>lateral offset</b>, <b>front photo spacing</b>, flight height, speed and gimbal angle, and the tool builds a <b>continuous mission</b> along the line.
</p>
<p>
When a <b>DEM</b> is provided, the flight can <b>follow the terrain</b>, adjusting waypoint altitudes to maintain a consistent height above ground.
</p>
<p>
The result is a <b>Litchi-compatible CSV</b> and optional flight line and waypoint layers in QGIS, ideal for mapping roads, corridors and other linear features.
</p>
"""

    figura = 'images/linear_flight.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6022">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                       layer_path=self.layer_path,
                       csv_path=self.csv_path,
                       kml_path=self.kml_path,
                       abrir_kml=self.abrir_kml)
        return {}
        