# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner H - Manually placed Side and Front distance data
                                 A QGIS plugin
 Flight Planner H
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli and Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from ..images.Imgs import *
import os

from .Funcs import (
    meters2degrees,
    azimute,
    loadParametros,
    saveParametros,
    processar_voo_horizontal,
    post_process_comum
)

class PlanoVoo_H_Manual(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooM, abGroundM, dlM, dfM, velocM, tStayM, gimbalM, csvM = loadParametros("H_Manual")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno', 'Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooM))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundM))
        self.addParameter(QgsProcessingParameterNumber('dl','Lateral Spacing Between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dlM))
        self.addParameter(QgsProcessingParameterNumber('df','Front Spacing Between Photos (m))',
                                                       type=QgsProcessingParameterNumber.Double, minValue=1,defaultValue=dfM))
        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocM))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayM))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalM))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvM))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        deltaLat = self.parameterAsDouble(parameters, 'dl', context)
        deltaFront = self.parameterAsDouble(parameters, 'df', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações =====================================================
        
        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Manual",
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['dl'],
                        df=parameters['df'])
        
        # =========================================================================================================
        # Sobreposições digitadas manualmente
        feedback.pushInfo(f"✅ Lateral Spacing: {deltaLat:.2f} m  Frontal Spacing: {deltaFront:.2f} m")

        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Converter Distâncias de mm para graus 
        centroide = poligono_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        # deltaLat e deltaFront em metros para o CSV
        deltaLat_g = meters2degrees(deltaLat, latitude_ref, crs)
        deltaFront_g = meters2degrees(deltaFront, latitude_ref, crs)

        # deltaFront em metros para o CSV
        deltaFront_m = deltaFront / meters2degrees(1, latitude_ref, crs)

        # Extrair coordenadas 
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])

        # Voo horizontal
        _, self.layer_path, self.kml_path = processar_voo_horizontal(
            linha_geom, poligono_geom, pol_pts, p1,
            deltaLat_g, deltaFront_g, deltaFront_m,
            altVoo, azimute, arquivo_csv,
            velocidade, tempo, gimbalAng, terrain, "HM", feedback)

        self.csv_path  = arquivo_csv
        self.abrir_kml = abrir_kml

        # ============= Encerramento ==========================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal Manual Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv, 'kml': self.kml_path}

    def name(self):
        return 'Flight_Plan_H_Manual'

    def displayName(self):
        return self.tr('2. Following terrain - Manual')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Manual()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))

    texto = """This tool enables drone flight planning for photogrammetry, following terrain elevations (optionally), and lateral and frontal overlaps are entered. And you can also choose the photo interval by <b>distance</b> or by <b>time</b>.</b><br>
It generates <b>CSV</b> file compatible with the <b>Litchi app</b> and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
"""

    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6020">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        post_process_comum(context, feedback,
                           layer_path=getattr(self, 'layer_path', None),
                           csv_path=getattr(self, 'csv_path', None),
                           kml_path=getattr(self, 'kml_path', None),
                           abrir_kml=getattr(self, 'abrir_kml', False))
        return {}

