# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Flight Planner H - Manually placed Side and Front distance data
                                 A QGIS plugin
 Flight Planner H
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-05
        copyright            : (C) 2024 by Prof Cazaroli e Leandro França
        email                : contato@geoone.com.br
***************************************************************************/
"""

__author__ = 'Prof Cazaroli and Leandro França'
__date__ = '2024-11-05'
__copyright__ = '(C) 2024 by Prof Cazaroli and Leandro França'
__revision__ = '$Format:%H$'

from qgis.core import *
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QCoreApplication, QUrl, QVariant
import processing
from ..images.Imgs import *
import os
import math
import numpy as np

from .Funcs import (
    gerar_CSV,
    meters2degrees,
    salvar_kml,
    azimute,
    loadParametros,
    saveParametros,
    csv_como_layer,
    distancia,
    pontos_na_linha,
    linhas_voo_poligono,
    heading_para_proximo,
    pontos_conexao
)

class PlanoVoo_H_Manual(QgsProcessingAlgorithm):
    def initAlgorithm(self, config=None):
        hVooM, abGroundM, dlM, dfopM, dfM, velocM, tStayM, gimbalM, csvM = loadParametros("H_Manual")

        self.addParameter(QgsProcessingParameterFeatureSource('terreno', 'Area', types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFeatureSource('primeira_linha','First line - direction flight', types=[QgsProcessing.TypeVectorLine]))
        self.addParameter(QgsProcessingParameterNumber('altura','Flight Height (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=2,defaultValue=hVooM))
        self.addParameter(QgsProcessingParameterBoolean('aboveGround', 'Above Ground (Follow Terrain)', defaultValue=abGroundM))
        self.addParameter(QgsProcessingParameterNumber('dl','Lateral Spacing Between Flight Lines (m)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,defaultValue=dlM))

        frontal = [self.tr('Distance (meters)'), self.tr('Time (seconds)')]
        self.addParameter(QgsProcessingParameterEnum('dfOpc', self.tr('Front Spacing Between Photos -- Options'), options = frontal, defaultValue= dfopM))
        self.addParameter(QgsProcessingParameterNumber('df','Front Spacing Between Photos -- Value',
                                                       type=QgsProcessingParameterNumber.Double, minValue=1,defaultValue=dfM))

        self.addParameter(QgsProcessingParameterNumber('velocidade','Flight Speed (m/s)',
                                                       type=QgsProcessingParameterNumber.Double, minValue=0.5,maxValue=20,defaultValue=velocM))
        self.addParameter(QgsProcessingParameterNumber('tempo','Time to Wait for Photo (seconds)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=0,maxValue=10,defaultValue=tStayM))
        self.addParameter(QgsProcessingParameterNumber('gimbalAng','Gimbal Angle (degrees)',
                                                       type=QgsProcessingParameterNumber.Integer, minValue=-90, maxValue=70, defaultValue=gimbalM))
        self.addParameter(QgsProcessingParameterBoolean('kml','Open KML on Google Earth',defaultValue=False))
        self.addParameter(QgsProcessingParameterFileDestination('saida_csv', 'Output CSV File (Litchi)', fileFilter='CSV files (*.csv)', defaultValue=csvM))

    def processAlgorithm(self, parameters, context, feedback):

        # ===== Parâmetros de entrada para variáveis ====================================================
        area_layer = self.parameterAsSource(parameters, 'terreno', context)
        primeira_linha = self.parameterAsSource(parameters, 'primeira_linha', context)
        altVoo = self.parameterAsDouble(parameters, 'altura', context)
        terrain = self.parameterAsBool(parameters, 'aboveGround', context)
        deltaLat = self.parameterAsDouble(parameters, 'dl', context)
        deltaFront = self.parameterAsDouble(parameters, 'df', context)
        deltaFrontOpc = self.parameterAsInt(parameters, 'dfOpc', context)
        velocidade = self.parameterAsDouble(parameters, 'velocidade', context)
        tempo = self.parameterAsDouble(parameters, 'tempo', context)
        gimbalAng = self.parameterAsDouble(parameters, 'gimbalAng', context)
        arquivo_csv = self.parameterAsFile(parameters, 'saida_csv', context)
        abrir_kml = self.parameterAsBool(parameters, 'kml', context)

        # ===== Verificações =====================================================
        
        if area_layer.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 polygon feature!")

        if primeira_linha.featureCount() != 1:
            raise QgsProcessingException("❌ Select 1 line feature!")

        feat_pol = next(area_layer.getFeatures())
        poligono_geom = feat_pol.geometry()
        if not poligono_geom or poligono_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid polygon geometry!")

        feat_lin = next(primeira_linha.getFeatures())
        linha_geom = feat_lin.geometry()
        if not linha_geom or linha_geom.isEmpty():
            raise QgsProcessingException("❌ Invalid line geometry!")

        num_vertices = sum(1 for _ in linha_geom.vertices())
        if num_vertices != 2:
            raise QgsProcessingException("❌ The line must contain exactly 2 vertices!")

        if 'saida_csv' not in parameters:
            raise QgsProcessingException("❌ Path to CSV file is empty!")
        if arquivo_csv and not os.path.exists(os.path.dirname(arquivo_csv)):
            raise QgsProcessingException("❌ Path to CSV file does not exist!")

        # ===== Grava Parâmetros =====================================================
        saveParametros("H_Manual",
                        h=parameters['altura'],
                        v=parameters['velocidade'],
                        t=parameters['tempo'],
                        gimbal=parameters['gimbalAng'],
                        csv=arquivo_csv,
                        abGround=parameters['aboveGround'],
                        dl=parameters['dl'],
                        df=parameters['df'],
                        dfop=parameters['dfOpc'])
        
        # ===== Sobreposições digitadas manualmente ====================================================

        if deltaFrontOpc == 0:
            feedback.pushInfo(f"✅ Lateral Spacing: {deltaLat:.2f} m  Frontal Spacing: {deltaFront:.2f} m")
        else:
            feedback.pushInfo(f"✅ Lateral Spacing: {deltaLat:.2f} m  Frontal Time: {deltaFront:.2f} s")

        # ===============================================================================
        # Reprojetar para WGS 84
        crs = area_layer.sourceCrs()
        crs_wgs = QgsCoordinateReferenceSystem('EPSG:4326')
        transformador = QgsCoordinateTransform(crs, crs_wgs, QgsProject.instance())

        poligono_geom.transform(transformador)
        linha_geom.transform(transformador)

        # Converter sensor de mm para graus 
        centroide = poligono_geom.centroid().asPoint()
        latitude_ref = centroide.y()

        deltaLat_g   = meters2degrees(deltaLat,   latitude_ref, crs)
        deltaFront_g = meters2degrees(deltaFront, latitude_ref, crs)

        # Extrair coordenadas da linha base e do polígono 
        if linha_geom.isMultipart():
            linha_pts = linha_geom.asMultiPolyline()[0]
        else:
            linha_pts = linha_geom.asPolyline()

        if poligono_geom.isMultipart():
            pol_pts = poligono_geom.asMultiPolygon()[0][0]
        else:
            pol_pts = poligono_geom.asPolygon()[0]

        p1 = QgsPointXY(linha_pts[0])
        p2 = QgsPointXY(linha_pts[1])

        # Gerar linhas de voo e montar LISTA_PONTOS em serpentina
        linhas_voo = linhas_voo_poligono(linha_geom, poligono_geom, pol_pts, p1, deltaLat)

        # Camada de linha de voo no QGIS (sem segmentos de conexão)
        nome_path = 'path - ' + os.path.splitext(os.path.basename(arquivo_csv))[0]
        layer_path = QgsVectorLayer('MultiLineString?crs=EPSG:4326', nome_path, 'memory')
        prov_path = layer_path.dataProvider()
        prov_path.addAttributes([QgsField('id', QVariant.Int)])
        layer_path.updateFields()
        multi_geom = QgsGeometry.collectGeometry([g for g in linhas_voo if g and not g.isEmpty()])
        feat_path = QgsFeature()
        feat_path.setGeometry(multi_geom)
        feat_path.setAttributes([1])
        prov_path.addFeatures([feat_path])
        layer_path.updateExtents()
        line_symbol = QgsLineSymbol.createSimple({'color': 'blue', 'width': '0.3'})
        seta = QgsMarkerSymbol.createSimple({'name': 'arrow', 'size': '5', 'color': 'blue', 'angle': '90'})
        marcador = QgsMarkerLineSymbolLayer()
        marcador.setInterval(30)
        marcador.setSubSymbol(seta)
        line_symbol.appendSymbolLayer(marcador)
        layer_path.setRenderer(QgsSingleSymbolRenderer(line_symbol))
        self.layer_path = layer_path

        LISTA_PONTOS = []
        direcao = 1
        for geom_linha in linhas_voo:
            if deltaFrontOpc == 0:   # por distância: pontos ao longo da linha
                pontos = pontos_na_linha(geom_linha, deltaFront_g, altVoo, azimute)
            else:                    # por tempo: apenas extremidades da linha
                pts = geom_linha.asMultiPolyline()[0] if geom_linha.isMultipart() else geom_linha.asPolyline()
                pontos = [
                    {'longitude': float(pts[0].x()),  'latitude': float(pts[0].y()),  'height': altVoo, 'bowangle': 0},
                    {'longitude': float(pts[-1].x()), 'latitude': float(pts[-1].y()), 'height': altVoo, 'bowangle': 0}
                ]

        # Garantir que o voo começa pelo lado de p1 
        # Se o primeiro ponto de LISTA_PONTOS está mais longe de p1 que o último, inverter tudo
        if LISTA_PONTOS:
            d_ini = (LISTA_PONTOS[0]['longitude']  - p1.x())**2 + (LISTA_PONTOS[0]['latitude']  - p1.y())**2
            d_fim = (LISTA_PONTOS[-1]['longitude'] - p1.x())**2 + (LISTA_PONTOS[-1]['latitude'] - p1.y())**2
            if d_fim < d_ini:
                LISTA_PONTOS.reverse()

        # ===== Heading: cada ponto aponta para o próximo waypoint =======================================
        heading_para_proximo(LISTA_PONTOS, azimute)

        feedback.pushInfo(f"✅ {len(LISTA_PONTOS)} waypoints generated across {len(linhas_voo)} flight line(s).")

        # ============= L I T C H I ==========================================================

        feedback.pushInfo("")

        if arquivo_csv and arquivo_csv.endswith('.csv'):
            gerar_CSV("H", LISTA_PONTOS, arquivo_csv, velocidade, tempo, deltaFront, 360, altVoo, gimbalAng, terrain, deltaFrontOpc)
            feedback.pushInfo("✅ CSV file successfully generated.")
        else:
            feedback.pushInfo("❌ CSV path not specified. Export step skipped.")

        # ============= Criar KML do caminho (path) ===============================================        
        base, ext = os.path.splitext(arquivo_csv)
        caminho_kml = base + ".kml"
        salvar_kml(caminho_kml, LISTA_PONTOS, nome_doc="flight_plan.kml")

        self.csv_path = arquivo_csv
        self.kml_path = caminho_kml
        self.abrir_kml = abrir_kml

        # ============= Mensagem de Encerramento =====================================================
        feedback.pushInfo("")
        feedback.pushInfo("✅ Horizontal Manual Flight Plan successfully executed.")
        feedback.pushInfo("")

        return {'csv': arquivo_csv,
                'kml': caminho_kml}

    def name(self):
        return 'Flight_Plan_H_Manual'

    def displayName(self):
        return self.tr('2. Following terrain - Manual')

    def group(self):
        return 'Horizontal Flight'

    def groupId(self):
        return 'horizontal'
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return PlanoVoo_H_Manual()

    def tags(self):
        return self.tr('Flight Plan,Measure,Topography,Plano voo,Plano de voo,voo,drone,GeoOne').split(',')

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'images/Horizontal.png'))

    texto = """This tool enables drone flight planning for photogrammetry, following terrain elevations (optionally), and lateral and frontal overlaps are entered. And you can also choose the photo interval by <b>distance</b> or by <b>time</b>.</b><br>
It generates <b>CSV</b> file compatible with the <b>Litchi app</b> and 2 Layers - <b>Flight Line</b> and <b>Photos Points</b>.
<p>It can also be used with other flight applications, utilizing the 2 genereted Layers for flight lines and waypoints.</p>
"""

    figura = 'images/Terrain_Follow.jpg'

    def shortHelpString(self):
        corpo = '''<div align="center">
                      <img src="'''+ os.path.join(os.path.dirname(os.path.dirname(__file__)), self.figura) +'''">
                      </div>
                      <div align="right">
                      <p><b>Learn more:</b><o:p></o:p></p>
                        <ul style="margin-top: 0cm;" type="disc">
                        <li><a href="https://geoone.com.br/pvplanodevoo">Sign up for GeoFlight Planner course</a><o:p></o:p></li>
                        <li><a href="https://portal.geoone.com.br/m/lessons/planodevoo?classId=6020">Click here to access the class with all the details about this tool!</a><o:p></o:p></li>
                        </ul>
                      <p align="right">
                      <b>Autores: Prof Cazaroli & Leandro França</b>
                      </p>
                      <a target="_blank" rel="noopener noreferrer" href="https://geoone.com.br/"><img title="GeoOne" src="data:image/png;base64,'''+ GeoOne +'''"></a>
					  <p><i>"Automated, easy and straight to the point mapping is at GeoOne!"</i></p>
                      </div>
                    </div>'''
        return self.tr(self.texto) + corpo
    
    
    def postProcessAlgorithm(self, context, feedback):        
        
        # ================= Carregar KML no QGIS =================
        layer_kml = None

        if hasattr(self, 'layer_path') and self.layer_path:
            QgsProject.instance().addMapLayer(self.layer_path)
            feedback.pushInfo("✅ Flight path layer added to QGIS.")
        
        # ================= Carregar CSV no QGIS =================
        layer_pontos = None

        if hasattr(self, 'csv_path') and self.csv_path:
            layer_pontos = csv_como_layer(self.csv_path, layer_name=None)

            if layer_pontos is None or not layer_pontos.isValid():
                feedback.reportError("❌ Could not load CSV as point layer.")
            else:
                QgsProject.instance().addMapLayer(layer_pontos)
                feedback.pushInfo("✅ CSV point layer added to QGIS.")

            try:
                params = { 'LAYER' : layer_pontos, 'STYLE_POINT' : 1 }
                processing.run("lftools:magicstyles", params)
            except:
                feedback.reportError("💡Install or enable the LFTools plugin to view the drone's heading, showing the direction its camera is pointing.")


        # ================= Abrir KML no Google Earth =================
        if hasattr(self, 'abrir_kml') and self.abrir_kml:
            if hasattr(self, 'kml_path') and self.kml_path and os.path.exists(self.kml_path):
                ok = QDesktopServices.openUrl(QUrl.fromLocalFile(self.kml_path))
                if ok:
                    feedback.pushInfo("✅ KML opened with the default application.")
                else:
                    feedback.reportError("⚠️ Could not open the KML automatically.")
            else:
                feedback.reportError("⚠️ KML path not found.")

        return {}

